### ISSUE TITLE
Linux VM fail to read admin_pass to reset the root password

### ISSUE THREAD

**Issue by archerslaw** [canonical/cloud-init#3]
If i specify the password when create a new linux VM in the console, but fail to read admin_pass to reset the root password with cloud-init agent. while the cloudbase-init agent for windows can read the admin_pass to reset the administrator password.

**Comment by TheRealFalcon** [comment]
Due to age and since this appears to be referring to cloudbase-init, rather than cloud-init, I'm going to close this issue. If there's still a problem here to be addressed by cloud-init, feel free to open a new issue.
