### ISSUE TITLE
unable to enable sysconfig renderer by changing the default priorities in cloud-init config

### ISSUE THREAD

**Issue by ani-sinha** [canonical/cloud-init#4131]
The issue is on RHEL8.7 and RHEL 9.2, can't run sysconfig when changing the priority of network renderers to: 

```
   network:
      renderers: ['sysconfig', 'netplan', 'network-manager', 'networkd', 'eni']
```

Version-Release number of selected component (if applicable):
cloud-init-23.1.1-3.el9

How reproducible:
100%

Steps to Reproduce:
1.Changing the priority of network renderers in /etc/cloud/cloud.cfg, for example, 
 'sysconfig' is the first one.
```
   network:
      renderers: ['sysconfig', 'netplan', 'network-manager', 'networkd', 'eni']
```
2.rm -rf /var/lib/cloud /var/log/cloud-init*  and reboot
3.It's network-manager selected not sysconfig

We can see it in /var/log/cloud-init.log
```
----------
2023-05-05 13:20:58,557 - __init__.py[DEBUG]: Selected renderer 'network-manager' from priority list: ['sysconfig', 'netplan', 'network-manager', 'networkd', 'eni']
----------
```

Expected results:
sysconfig is selected when its priority is higher than network-manager.

This is because RHEL 8 and RHEL 9 as far as I can see, does not ship with ifup and ifdown scripts.

**Comment by TheRealFalcon** [comment]
What OS and OS version?

The cloud-init sysconfig renderer will only run on a limited number of distros. In addition, the renderer requires:
1. `ifup` and `ifdown` exist in either `/sbin` or `/usr/sbin`
2. Either `/etc/sysconfig/network-scripts/network-functions` or `/etc/sysconfig/config` exists on the filesystem

If these aren't true, cloud-init won't use the sysoncifg renderer regardless of ordering. Are these cases true for you?

**Comment by ani-sinha** [comment]
> What OS and OS version?

RHEL 9.2 or CenOS 9 stream.

> 
> The cloud-init sysconfig renderer will only run on a limited number of distros. In addition, the renderer requires:
> 
> 1. `ifup` and `ifdown` exist in either `/sbin` or `/usr/sbin`
> 2. Either `/etc/sysconfig/network-scripts/network-functions` or `/etc/sysconfig/config` exists on the filesystem
> 
> If these aren't true, cloud-init won't use the sysoncifg renderer regardless of ordering. Are these cases true for you?

Yes. We do not ship ifup and ifdown scripts with RHEL 8/9 or Centos images. I have checked version 8.7 and 9.2.

**Comment by ani-sinha** [comment]
> > What OS and OS version?
> 
> RHEL 9.2 or CenOS 9 stream.
> 
> > The cloud-init sysconfig renderer will only run on a limited number of distros. In addition, the renderer requires:
> > 
> > 1. `ifup` and `ifdown` exist in either `/sbin` or `/usr/sbin`
> > 2. Either `/etc/sysconfig/network-scripts/network-functions` or `/etc/sysconfig/config` exists on the filesystem
> > 
> > If these aren't true, cloud-init won't use the sysoncifg renderer regardless of ordering. Are these cases true for you?
> 
> Yes. We do not ship ifup and ifdown scripts with RHEL 8/9 or Centos images. I have checked version 8.7 and 9.2.

Proposed fix https://github.com/canonical/cloud-init/pull/4132 .
It came out of our internal testing.
