### ISSUE TITLE
Proposal for More Detailed, Repository-Specific Contributing Guides

### ISSUE THREAD

**Issue by ibilalkayy** [canonical/cloud-init#4137]
Hello, I have been reviewing numerous GitHub repositories in this organization and I have noticed a lack of comprehensive contributing guides. While some repositories do have guides, they tend to merely instruct contributors to sign a contributing agreement license, which in my opinion, does not provide sufficient information.

It's also been observed that many issue tabs direct users to https://opensource.guide/. While this is a helpful resource, but it provides a general overview of contributing to any open-source project, rather than specific guidance for the respective repository.

I believe that each repository could greatly benefit from a detailed, repository-specific contributing guide. Such guides would be immensely beneficial for new contributors, as it would provide clear direction and streamline their onboarding process.

Thank you for your time and consideration! If this is really an issue then I would be really happy to add the contribution to all the respositories.

**Comment by TheRealFalcon** [comment]
@ibilalkayy , I'm going to close this as cloud-init already has a fairly detailed CONTRIBUTING.rst . If you have any specific feedback or suggestions, please let us know!
