### ISSUE TITLE
[docs]: The font used is very hard to read

### ISSUE THREAD

**Issue by ToddEricksonCR** [canonical/cloud-init#4146]
# Documentation request
The font used on your website is very hard to read. It is very washed out. Especially the blue hyperlinks

---
*Reported from: https://cloudinit.readthedocs.io/en/latest/explanation/configuration.html*

**Comment by holmanb** [comment]
@ToddEricksonCR Thanks for filing this issue.

Could you please include some information to help us understand the issue you are seeing? Specifically: browser type and version, active add-ons, and a screenshot of what you see?

**Comment by igalic** [comment]
thanks for the detailed report

**Comment by s-makin** [comment]
Thanks for your feedback @jimboolio - your screenshots are really helpful, and I can see exactly what you mean about the dark mode. The contrast problem is definitely exacerbated there by the font being thin. I'll see what I can do about improving the style on both dark and light mode - and having had some feedback about the font I'll try out some different ones to see if that helps the problem.

**Comment by tedz2usa** [comment]
I also found the combination of selected font family and font weight is too thin, making it hard to read the documentation. 

The issue stems from these two css declarations: 
in the `<style> tag` inside of `document <head>`:

    body {
        ...
        --font-stack: Ubuntu, -apple-system, Segoe UI, Roboto, Oxygen, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
        ...    
    }


in `_static/css/custom.css`:

    div.page, li.scroll-current>.reference, dl.glossary dt, dl.simple dt, dl:not([class]) dt {
        font-weight: 300;
        line-height: 1.5;
        font-size: var(--font-size--normal);
    }
    
My Mac (MacOS 12.4 Monterey) does not have any of these first fonts in the font stack: `Ubuntu, -apple-system, Segoe UI, Roboto, Oxygen, Cantarell, Fira Sans, Droid Sans`. Therefore, `Helvetica Neue` is my browser's (Chrome) chosen font to render this page.  Unfortunately `Helvetica Neue` at `font-weight 300` is too thin to read for general body text (in my opinion). 

One way to alleviate this issue to set this font-weight rule to 400.

You can execute this in your browser console to get this effect right away:

    (() => { 
        document.head.appendChild(document.createElement('style')).innerHTML = 
            'div.page, li.scroll-current>.reference, dl.glossary dt, dl.simple dt, dl:not([class]) dt { font-weight: 400 }'; 
        }
    )()


Or, even make a (bookmarklet shortcut)[https://en.wikipedia.org/wiki/Bookmarklet] in your bookmarks bar, to easily activate this new style rule:

    javascript:(() => { document.head.appendChild(document.createElement('style')).innerHTML = 'div.page, li.scroll-current>.reference, dl.glossary dt, dl.simple dt, dl:not([class]) dt { font-weight: 400 }'; })()

**Comment by blackboxsw** [comment]
It's likely that this changeset in cloud-init would impact the sphinx setup and configuration during doc build in the file `doc/rtd/conf.py` with supplemental configuration CSS or JS  in the config options: `html_css_files` or `html_js_files`.

To generate and test docs locally:
````
tox -e doc
xdg-open doc/rtd_html/index.html
```
