### ISSUE TITLE
 subiquity fails to see autoinstall user-data conveyed by cloud-init 23.2

### ISSUE THREAD

**Issue by blackboxsw** [canonical/cloud-init#4158]
# Bug report
Reflected from upstream subiquity bug LP: #2022102 for tracking/reference in cloud-init as this would be a blocker to cloud-init SRU of 23.2 to earlier Stable release as it can break server live-installer ISOs.

This bug is due to older versions of cloud-init packaged within the subiqutiy snap failing to `cloudinit.sources.pkl_load` the cached /var/lib/cloud/instance/obj.pkl which was created by the newer cloud-init 23.2 code.

Tracebacks seen in live-installer ephemeral environment /var/log/installer/subiquity-server-debug.log:
```
2023-06-01 17:58:08,127 WARNING cloudinit.sources:1715 Failed loading pickled blob from /var/lib/cloud/instance/obj.pkl
2023-06-01 17:58:08,127 DEBUG cloudinit.sources:1724 Failed loading pickled blob from /var/lib/cloud/instance/obj.pkl
Traceback (most recent call last):
  File "/snap/subiquity/4709/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 1133, in pkl_load
    return pickle.loads(pickle_contents)
AttributeError: Can't get attribute 'IscDhclient' on <module 'cloudinit.net.dhcp' from '/snap/subiquity/4709/usr/lib/python3/dist-packages/cloudinit/net/dhcp.py'>
```

While cloud-init supports backward-compatibility across upgrade path for `pkl_load` for newer versions, older versions can still fail to `pkl_load` cached pickles which reference classes which don't exist

## Steps to reproduce the problem
1. Download [ubuntu server daily mantic ISO](https://cdimage.ubuntu.com/ubuntu-server/daily-live/20230531/mantic-live-server-amd64.iso)
2. Launch live ISO image with KVM:
```
sudo kvm -name ci-test-kvm-live-server-ephemeral-1 -m 3G -net nic -D /tmp/qemu.log -cdrom /srv/iso/mantic/mantic-live-server-amd64.iso
```
4. Select "Help -> Enter Shell" in text console UX
5. See undesirable traceback in subiquity-server-debug.log
```
# grep -A 4 Traceback /var/log/installer/subiquity-server-debug.log

root@ubuntu-server:~# grep -A 4 Traceback /var/log/installer/subiquity-server-debug.log
Traceback (most recent call last):
  File "/snap/subiquity/4709/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 1133, in pkl_load
    return pickle.loads(pickle_contents)
AttributeError: Can't get attribute 'IscDhclient' on <module 'cloudinit.net.dhcp' from '/snap/subiquity/4709/usr/lib/python3/dist-packages/cloudinit/net/dhcp.py'>
2023-06-01 17:58:08,127 DEBUG cloudinit.stages:318 no cache found
```

## Environment details
- Cloud-init version: 22.3 (on live-server daily ISO dated May 31)
- Operating System Distribution: Ubuntu mantic
- Cloud provider, platform or installer type: live-server ISOs

## cloud-init logs
No Tracebacks in cloud-init logs, but errors in /var/log/installer/subiquity-server-debug.log

[LP: #2022102](https://bugs.launchpad.net/subiquity/+bug/2022102)

**Comment by holmanb** [comment]
> Reflected from upstream subiquity bug LP: #2022102 for tracking/reference in cloud-init as this would be a blocker to cloud-init SRU of 23.2 to earlier Stable release as it can break server live-installer ISOs.

This isn't an upstream cloud-init problem. Wouldn't it be better to file this sort of bug [here](https://bugs.launchpad.net/ubuntu/+source/cloud-init/+filebug), per [the docs](https://cloudinit.readthedocs.io/en/latest/howto/bugs.html#distro-specific-issues)?

**Comment by blackboxsw** [comment]
Created a downstream launchpad bug task for this. Since it is not specifically a cloud-init problem, but an environmental problem caused by older versions of cloud-init trying to unpickle the cached DataSource @ `/var/lib/cloud/instance/obj.pkl` which was pickled by a newer version of cloud-init, this downgrade path is not officially supported. That said, a [feature branch](https://github.com/blackboxsw/cloud-init/tree/SC-1452-persist-run-combined-cloud-config-json) in progress will likely provide an alternative to obtain `/run/cloud-init/combined-cloud-config.json` to allow live installer environment to obtain final merged cloud config without having to use `Init().read_cfg()` to unpickle and load merged configuration key/values.
