### ISSUE TITLE
[docs]: what vars are available in cc_ntp.config.template ?

### ISSUE THREAD

**Issue by aciba90** [canonical/cloud-init#4166]
# Documentation request

In the ntp config module, users can give their own template to be rendered as ntp configuration under the key cc_ntp.config.template.

It is not obvious what variables are available to be used in the template. There is one example including a subset of the variables, but I think a full list of the variables would be useful.

---
*Reported from: https://cloudinit.readthedocs.io/en/latest/reference/modules.html*

**Comment by aciba90** [comment]
Tracking in SC-1570

**Comment by MjMoshiri** [comment]
Hi,
I would like to work on this. what is intended to be done here as the properties are available in the [JSON](https://github.com/canonical/cloud-init/blob/8d9da9024de96c8f3afd0030fea009736cf6bc3b/cloudinit/config/schemas/schema-cloud-config-v1.json#L1832) file too? should the guide be added in string format at the end of the description? or in the example format?

**Comment by aciba90** [comment]
Thanks @MjMoshiri for making cloud-init better. I think the target is to document [here](https://cloudinit.readthedocs.io/en/latest/reference/modules.html#ntp) that the variables available for the template are the ones from [here](https://github.com/canonical/cloud-init/blob/b669f31c3d06023c9d55d59ff797515a598db246/cloudinit/config/cc_ntp.py#L500-L505).

To do so is probably sufficient to extend the description of [ntp.config.template](https://github.com/canonical/cloud-init/blob/b669f31c3d06023c9d55d59ff797515a598db246/cloudinit/config/schemas/schema-cloud-config-v1.json#L1906).

**Comment by MjMoshiri** [comment]
> Thanks @MjMoshiri for making cloud-init better. I think the target is to document [here](https://cloudinit.readthedocs.io/en/latest/reference/modules.html#ntp) that the variables available for the template are the ones from [here](https://github.com/canonical/cloud-init/blob/b669f31c3d06023c9d55d59ff797515a598db246/cloudinit/config/cc_ntp.py#L500-L505).
> 
> To do so is probably sufficient to extend the description of [ntp.config.template](https://github.com/canonical/cloud-init/blob/b669f31c3d06023c9d55d59ff797515a598db246/cloudinit/config/schemas/schema-cloud-config-v1.json#L1906).

Hi, @aciba90  I sent the [PR](https://github.com/canonical/cloud-init/pull/4378) related to the issue. Apart from the Parameters, I also added a Link to Jinja Template docs in case someone needed help with that. please let me know. 🙏🏻

**Comment by blackboxsw** [comment]
Thanks @MjMoshiri for submitting a PR, if you can sign the contributor agreement (commented on your PR)  we'll take that changeset right away. Thanks again!
