### ISSUE TITLE
[enhancement]: Deprecate DatasourceDigitalOcean 

### ISSUE THREAD

**Issue by aciba90** [canonical/cloud-init#4172]
# Enhancement

Issue a warning log advertising DatasourceDigitalOcean is deprecated.

In order to make clear for users and developers about the fact that DatasourceDigitalOcean is not maintained, as the official DO images override it with DatasourceConfigDrive. More context: https://github.com/canonical/cloud-init/pull/4130#issuecomment-1573884030

**Comment by tyb-truth** [comment]
hi team, would appreciate getting assigned if no one else is working on this.
