### ISSUE TITLE
/run is not ephemeral on *BSD

### ISSUE THREAD

**Issue by igalic** [canonical/cloud-init#4180]
# Bug report

cloud-init sets up a `Paths.run_dir` which on Linux is the ephemeral `/run` directory.
On BSD, the corresponding directory would be `/var/run`, but we don't change that path. `/run` is non-standard. (See [`hier(7)`](https://man.freebsd.org/cgi/man.cgi?query=hier&apropos=0&sektion=7&manpath=FreeBSD+14.0-CURRENT&arch=default&format=html))

That means that cloud-init potentially behaves very differently on BSD

## Steps to reproduce the problem

1. boot a cloud-init enabled BSD system.
2. disable cloud-init.
3. `/run/cloud-init` still exists

## Environment details
- Cloud-init version: all
- Operating System Distribution: *BSD
- Cloud provider, platform or installer type: all

**Comment by blackboxsw** [comment]
Cloud-init will still write each file on reboot for BSD like other distributions.

But, if cloud-init is disabled via `/etc/cloud/cloud-init.disabled` (or by kernel commandline) or can no longer detect any datasource, it's likely *BSD will have stale files around in /run/cloud-init across reboot that Linux distributions would have magically cleared.

**Comment by loth** [comment]
This would fix #4231 if implemented

**Comment by igalic** [comment]
can you try by replacing /run with a link to /var/run ? that one should be ephemeral, in that it's cleared before cloudinitlocal
