### ISSUE TITLE
[enhancement]:  Improve the functionality of "cloud-init schema --config-file" validation

### ISSUE THREAD

**Issue by forrie** [canonical/cloud-init#4186]
# Enhancement

The current implementation of this is very basic, often producing errors that are not in origin.  In my case, I can go to a simple Yaml validator or beautifier online and get the information I need.   This process should be made more useful for what is otherwise a very sensitive file format. Small errors are often difficult to identify.    Perhaps also consider adopting alternative formats that aren't as prone to sensitivity like XML.

**Comment by holmanb** [comment]
> The current implementation of this is very basic, often producing errors that are not in origin.

What do you mean "not in origin"? Can you please give an example?

> This process should be made more useful for what is otherwise a very sensitive file format.

We always want to improve user experience with cloud-init. Could you please specify what, exactly, you want improved? The schema subcommand validates your config against the cloud-init [user data cloud-config schema](https://github.com/canonical/cloud-init/blob/main/cloudinit/config/schemas/schema-cloud-config-v1.json). This will tell you if you are providing a configuration that has invalid keys / values. Are you requesting better validation of the yaml format itself? Or is there some specific error that is confusing? If you could give an example of output that isn't what you like and some direction of what could done to improve it, that would significantly improve this feature request (and the likelyhood of implementation). 

> Small errors are often difficult to identify.

Examples please.

> Perhaps also consider adopting alternative formats that aren't as prone to sensitivity like XML.

I doubt that XML is in the future of cloud-config user data format, but if user desire exists, I'm sure we would seriously consider it. That is a different request from the rest of this bug, however, so please file a separate bug that we can use for tracking user interest if you'd like to see that happen.

**Comment by forrie** [comment]
I had responded via email to this, but looks like it never got here.  

YAML seems better suited for smaller configuration sets, which are easier to compose, define and debug.  Due to its sensitivity and the potential complexity of cloud-config/autoinstall configurations, an alternative would be better.

I appreciate that XML would be too verbose.  I also realize that YAML being a superset of JSON supports more features that make it useful for this application.  JSON doesn't support comments, and a few other things.

Once I finally got a working YAML, I have been gradually adding the features I need -- and indeed having to invest more time debugging them, including again today, which includes test-rolling them into a VMware image; it's incredibly time consuming.

The issue of documentation and a better linting function remains.  My task might have been made easier had we a "pretty print" program that would format a YAML file specifically for autoinstall -- which would take into account all the configuration tags, their dependencies and format/indent properly, remove tabs, etc.   But who's going to write and maintain it. 

Please consider a flexible alternative to YAML for configuring autoinstall?

**Comment by holmanb** [comment]
> Please consider a flexible alternative to YAML for configuring autoinstall?

No.

Your request is against the wrong project. Subiquity is the autoinstaller. You can file a bug there if you would like them to change something.

**Comment by holmanb** [comment]
Statements that amount to "my workflow isn't ideal" and "the docs and linting could be better" don't contribute to this project in a meaningful way. We (the developers) know that things could be better and are always working on improving them. Vague complaints are a drain of project developer time.

If you have any specific technical request for changes to `cloud-init schema --config-file` or anything else, please add them here in detail. Otherwise I will close this issue as invalid.

My previous statements about XML stand.
