### ISSUE TITLE
cloud-init "x-shellscript-per-boot" does not trigger on reboot

### ISSUE THREAD

**Issue by sujeetkp** [canonical/cloud-init#4197]
I am using terraform to configure cloud-init. I used "x-shellscript-per-boot" to trigger my script on every reboot, but it does not work. It triggers only once when the instance is created.

     data "cloudinit_config" "provision" {
        gzip          = false
        base64_encode = true
      
        # Creates a script on the server at a particular location
        part {
          content_type = "text/cloud-config"
          content      = local.cloud_config_config
        }
        /*
        part {
          content_type = "text/x-shellscript"
          filename     = "example.sh"
          content  = <<-EOT
            #!/bin/bash
            echo "Hello World"
            /opt/userdata/userdata.sh
          EOT
         }
         */
      
        // This does NOT work. As per the documentation, this script should trigger on reboot.
        part {
          content_type = "x-shellscript-per-boot"
          filename     = "example.sh"
          content  = <<-EOT
            #!/bin/bash
            echo "Hello World"
            /opt/userdata/userdata.sh
          EOT
        }
      
      }

**Userdata**

    azureuser@example-machine:~$ curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/userData?api-version=2021-01-01&format=text" | base64 --decode
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  3652  100  3652    0     0   324k      0 --:--:-- --:--:-- --:--:--  297k
    Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
    MIME-Version: 1.0
    
    --MIMEBOUNDARY
    Content-Transfer-Encoding: 7bit
    Content-Type: text/cloud-config
    Mime-Version: 1.0
    
    #cloud-config
    "write_files":
    - "content": "IyEvYmluL2Jhc2gKCmVjaG8gIkxvZ2dlZCBpbiBhcyAkKHdob2FtaSkgISEiCgplY2hvICJTbGVlcGluZyAuLi4iCnNsZWVwIDEyMAoKIyBJbnN0YWxsIERvY2tlcgoKZGF0ZSA+IC90bXAvZGF0ZS5sb2cKCmFwdC1nZXQgLXkgdXBkYXRlCmFwdC1nZXQgLXkgaW5zdGFsbCBjYS1jZXJ0aWZpY2F0ZXMgY3VybCBnbnVwZwoKaW5zdGFsbCAtbSAwNzU1IC1kIC9ldGMvYXB0L2tleXJpbmdzCmN1cmwgLWZzU0wgaHR0cHM6Ly9kb3dubG9hZC5kb2NrZXIuY29tL2xpbnV4L3VidW50dS9ncGcgfCBncGcgLS1kZWFybW9yIC1vIC9ldGMvYXB0L2tleXJpbmdzL2RvY2tlci5ncGcKY2htb2QgYStyIC9ldGMvYXB0L2tleXJpbmdzL2RvY2tlci5ncGcKCmVjaG8gXAogICJkZWIgW2FyY2g9IiQoZHBrZyAtLXByaW50LWFyY2hpdGVjdHVyZSkiIHNpZ25lZC1ieT0vZXRjL2FwdC9rZXlyaW5ncy9kb2NrZXIuZ3BnXSBodHRwczovL2Rvd25sb2FkLmRvY2tlci5jb20vbGludXgvdWJ1bnR1IFwKICAiJCguIC9ldGMvb3MtcmVsZWFzZSAmJiBlY2hvICIkVkVSU0lPTl9DT0RFTkFNRSIpIiBzdGFibGUiIHwgXAogIHRlZSAvZXRjL2FwdC9zb3VyY2VzLmxpc3QuZC9kb2NrZXIubGlzdCA+IC9kZXYvbnVsbAoKYXB0LWdldCAteSB1cGRhdGUKYXB0LWdldCAteSBpbnN0YWxsIGRvY2tlci1jZSBkb2NrZXItY2UtY2xpIGNvbnRhaW5lcmQuaW8gZG9ja2VyLWJ1aWxkeC1wbHVnaW4gZG9ja2VyLWNvbXBvc2UtcGx1Z2luCgojIEluc3RhbGwgQVogQ0xJCgphcHQtZ2V0IC15IHVwZGF0ZQphcHQtZ2V0IC15IGluc3RhbGwgY2EtY2VydGlmaWNhdGVzIGN1cmwgYXB0LXRyYW5zcG9ydC1odHRwcyBsc2ItcmVsZWFzZSBnbnVwZwoKbWtkaXIgLXAgL2V0Yy9hcHQva2V5cmluZ3MKY3VybCAtc0xTIGh0dHBzOi8vcGFja2FnZXMubWljcm9zb2Z0LmNvbS9rZXlzL21pY3Jvc29mdC5hc2MgfAogICAgZ3BnIC0tZGVhcm1vciB8CiAgICB0ZWUgL2V0Yy9hcHQva2V5cmluZ3MvbWljcm9zb2Z0LmdwZyA+IC9kZXYvbnVsbApjaG1vZCBnbytyIC9ldGMvYXB0L2tleXJpbmdzL21pY3Jvc29mdC5ncGcKCkFaX1JFUE89JChsc2JfcmVsZWFzZSAtY3MpCmVjaG8gImRlYiBbYXJjaD1gZHBrZyAtLXByaW50LWFyY2hpdGVjdHVyZWAgc2lnbmVkLWJ5PS9ldGMvYXB0L2tleXJpbmdzL21pY3Jvc29mdC5ncGddIGh0dHBzOi8vcGFja2FnZXMubWljcm9zb2Z0LmNvbS9yZXBvcy9henVyZS1jbGkvICRBWl9SRVBPIG1haW4iIHwKICAgIHRlZSAvZXRjL2FwdC9zb3VyY2VzLmxpc3QuZC9henVyZS1jbGkubGlzdAoKYXB0LWdldCAteSB1cGRhdGUKYXB0LWdldCAteSBpbnN0YWxsIGF6dXJlLWNsaQoKIyBMb2dpbiB0byBBQ1IgYW5kIHB1bGwgaW1hZ2UKCmF6IGxvZ2luIC1pIC0tdXNlcm5hbWUgMmY0ZjlkOGYtMWNlYy00NTgyLThlNTEtOGZkMjEyODk5ZDYyCmF6IGFjciBsb2dpbiAtLW5hbWUgYWNyZGVtb2NvbnRhaW5lci5henVyZWNyLmlvCmRvY2tlciBwdWxsIGFjcmRlbW9jb250YWluZXIuYXp1cmVjci5pby9uZ2lueDpsYXRlc3QKZG9ja2VyIHJ1biAtZCAtLW5hbWUgbmdpbnggLXAgODA4MDo4MCBhY3JkZW1vY29udGFpbmVyLmF6dXJlY3IuaW8vbmdpbng6bGF0ZXN0CmN1cmwgbG9jYWxob3N0OjgwODAK"
      "encoding": "b64"
      "owner": "root:root"
      "path": "/opt/userdata/userdata.sh"
      "permissions": "0755"
    
    
    --MIMEBOUNDARY
    Content-Disposition: attachment; filename="example.sh"
    Content-Transfer-Encoding: 7bit
    Content-Type: x-shellscript-per-boot
    Mime-Version: 1.0
    
    #!/bin/bash
    echo "Hello World"
    /opt/userdata/userdata.sh
    
    --MIMEBOUNDARY--

**Comment by blackboxsw** [comment]
Given that your script also emits "Hello world" you should `grep -i "hello world" /var/log/cloud-init-output.log" to assert that minimally that message is seen once per boot.

**Comment by holmanb** [comment]
It looks like we were not able to reproduce, we have stronger testing around this behavior, and no followup from the reporter. Closing. Feel free to reopen if you have more details to report.

**Comment by ei-grad** [comment]
Probably the issue was caused by improper content type specified:
```
      content_type = "x-shellscript-per-boot"
```
Which should be `text/x-shellscript-per-boot`.
