### ISSUE TITLE
Broken link to the hacking document

### ISSUE THREAD

**Issue by lindhe** [canonical/cloud-init#4229]
https://github.com/canonical/cloud-init/blob/fbcb224bc12495ba200ab107246349d802c5d8e6/README.md?plain=1#L46

![image](https://github.com/canonical/cloud-init/assets/7773090/4e96ea9a-983d-494f-a692-a9d7edf2a961)

**Comment by rishitashaw** [comment]
Hello! I'm interested in working on this issue. I suggest replacing the broken link with this working link: https://cloudinit.readthedocs.io/en/latest/development/contributing.html. It provides relevant information on hacking and contributing. Let me know if you agree. Thanks!

**Comment by holmanb** [comment]
This is correct on the main branch. Where did you see this old commit?

**Comment by lindhe** [comment]
Eh, yeah wtf? Why did I link a 2 year old commit? I have honestly no idea how I got there. Sorry. 😂
