### ISSUE TITLE
[docs]: duplicated integration testing entry

### ISSUE THREAD

**Issue by aciba90** [canonical/cloud-init#4242]
# Documentation request

There are two `Integration testing` buttons, one under `Testing` and one under `Development`, both pointing to the same [page](https://canonical-cloud-init.readthedocs-hosted.com/en/latest/development/integration_tests.html#).

I believe it would be simpler to have only one of them.

https://pasteboard.co/MXKRui5niILg.png

---
*Reported from: https://canonical-cloud-init.readthedocs-hosted.com/en/latest/development/integration_tests.html*

**Comment by TheRealFalcon** [comment]
@rishitashaw , thanks for signing up, and feel free to submit a PR! Removing the `Testing` dropdown would be the best way to do it so that we have a flatter hierarchy under `Development`.
