### ISSUE TITLE
Don't change log permissions if they are already more restrictive

### ISSUE THREAD

**Issue by TheRealFalcon** [canonical/cloud-init#4243]
Because #4093, we modified the cloud-init log permissions to always be 640 to prevent logs with more open permissions from leaking sensitive information. This is undesireable for those that want stricter permissions, such as 600. We should enforce 640 or stricter, but if the file is already stricter, don't change back to 640.

**Comment by holmanb** [comment]
> We should enforce 640 or stricter, but if the file is already stricter, don't change back to 640.


Due to a buggy implementation in #4250, we do not enforce 640 or stricter. Reopening.
