### ISSUE TITLE
cloud-init sets incorrect default gateway

### ISSUE THREAD

**Issue by cmonty14** [canonical/cloud-init#4246]
# Bug report
I have deployed a VM with 3 interfaces identified by OS as:
ens192, ens224, ens256

Each interface gets its configuration via DHCP.
This configuration is generally correct, however a wrong default gateway is set.

In my observation the default gateway set depends on the first interface configured (by cloud-init).
In my VM this is never the "first" interface attached to the VM, instead the default gateway is set for ens224.

In [cloud-init docu](https://cloudinit.readthedocs.io/en/latest/reference/network-config.html) one can find:
_User data cannot change an instance’s network configuration. In the absence of network configuration in any of the above sources, cloud-init will write out a network configuration that will issue a DHCP request on a “first” network interface._

This would actually match to my observation.
But then the question is: which interface is treated as first interface by cloud-init.
And how can I influence this?

Again, in 99% of my VMs this is not the first interface attached to the VM.

Can I define a cloud-init configuration that sets a default gateway independant of the attached interface (and its DHCP) config.

## Steps to reproduce the problem
1. cloud-init clean --logs
2. cloud-init init--local
3. ls -l /etc/sysconf/network
4. ip route

![2023-07-13_16-18-59](https://github.com/canonical/cloud-init/assets/12523591/cb81e42e-893a-446f-9375-85a9f7cf1490)

## Environment details
- Cloud-init version: 23.1-150100.8.63.5
- Operating System Distribution: SLES 15SP3
- Cloud provider, platform or installer type: OpenStack

## cloud-init logs
[cloud-init.tar.gz](https://github.com/canonical/cloud-init/files/12040609/cloud-init.tar.gz)

**Comment by dermotbradley** [comment]
cloud-init gets the network configure from the OpenStack metadata server. The config can be seen in the cloud-init.log file that you provided:

```
2023-07-13 14:14:49,807 - stages.py[DEBUG]: applying net config names for {'version': 1, 'config': [{'type': 'physical', 'mtu': 8950, 'subnets': [{'type': 'dhcp4'}], 'mac_address': 'fa:16:3e:f3:65:f4', 'name': 'ens192'}, {'type': 'physical', 'mtu': 8950, 'subnets': [{'type': 'dhcp4'}], 'mac_address': 'fa:16:3e:08:c2:08', 'name': 'ens224'}, {'type': 'physical', 'mtu': 8950, 'subnets': [{'type': 'dhcp4'}], 'mac_address': 'fa:16:3e:69:2e:23', 'name': 'ens256'}]}
```

cloud-init then "renders" this config into sysconfig files for SLES:

```
2023-07-13 14:14:49,818 - __init__.py[DEBUG]: Selected renderer 'sysconfig' from priority list: None
2023-07-13 14:14:49,831 - util.py[DEBUG]: Writing to /etc/sysconfig/network/ifcfg-ens192 - wb: [644] 136 bytes
2023-07-13 14:14:49,832 - util.py[DEBUG]: Writing to /etc/sysconfig/network/ifcfg-ens224 - wb: [644] 136 bytes
2023-07-13 14:14:49,833 - util.py[DEBUG]: Writing to /etc/sysconfig/network/ifcfg-ens256 - wb: [644] 136 bytes
```

No default route (or any other route) was specified in the configuration provided by OpenStack.

Therefore the default route must be set by SLES when it brings up all the interfaces via DHCP and this is nothing to do with cloud-init. I assume either 
that only on the ens224 interface is the DHCP server's reply specifying a default route, or else that on multiple interfaces the DHCP server's reply specified a default route but SLES only set a single default route.

I don't see how this is a cloud-init issue.

**Comment by cmonty14** [comment]
I agree with your conclusion that network configuration is done based on OpenStack metadata server.
There's no issue with this, means interfaces ens192, ens224, ens256 are configured correctly using DHCP.

However, there should be a "first" interface that would be treated with higher priority.
Again I'm referring to [cloud-init docu](https://cloudinit.readthedocs.io/en/latest/reference/network-config.html):
_User data cannot change an instance’s network configuration. In the absence of network configuration in any of the above sources, cloud-init will write out a network configuration that will issue a DHCP request on a “first” network interface._

Or is there no "first" interface because of OpenStack metadata server data?

**Comment by dermotbradley** [comment]
> However, there should be a "first" interface that would be treated with higher priority. Again I'm referring to [cloud-init docu](https://cloudinit.readthedocs.io/en/latest/reference/network-config.html): _User data cannot change an instance’s network configuration. In the absence of network configuration in any of the above sources, cloud-init will write out a network configuration that will issue a DHCP request on a “first” network interface._

Nope, if you read that section carefully it says

User data cannot change an instance’s network configuration. **In the absence of network configuration in any of the above sources**, cloud-init will write out a network configuration that will issue a DHCP request on a “first” network interface.

However you have agreed with me that network configuration is being obtained from OpenStack (whether via either ConfigDrive or OpenStack datasource) and so the above text is not relevant (it is describing the "fallback" DHCP network configuration method).

> In case there's no "first" interface, could you please advise how to create a custom network configuration that sets a default gateway and depending DNS via DHCP for specific interface ens192?

That is under the control of your Openstack deployment and/or your DHCP server(s).

**Comment by cmonty14** [comment]
OK. Thanks for clarification.

My intention now is to use a cloud-init configuration file that defines
- default gateway
- DNS

for the primary interface ens192.

For this I created this file:
```
# cat /etc/cloud/cloud.cfg.d/01-iface-ens192.cfg
network:
  version: 2
  ethernets:
    ens192:
      dhcp4: true
      dhcp-identifier: fa:16:3e:09:c7:dd
      dhcp-route-via-dhcp: true
      dhcp-restore-default-route: true
      dhcp-hostname: myserver.example.com
      nameservers:
        dhcp4: true
```
However, this configuration does not fix my error: wrong default gateway.

Do I need to create other cloud-init config files for each interface ens224 and ens256?
Does cloud-init prefer data from the OpenStack metadata server over cloud-init config files?
Can I use a mixture of OpenStack metadata server and cloud-init config files? If yes, which config gets higher priority?

**Comment by aciba90** [comment]
The code executed to render sysconfig configs is [cloudinit/net/sysconfig.py](https://github.com/canonical/cloud-init/blob/392346ccd5d205e931efcc11892d7e32efc439ca/cloudinit/net/sysconfig.py) but SLE carries on a [cloud-init-write-routes.patch](https://download.opensuse.org/repositories/Cloud:/Tools/SLE_15_SP4/src/cloud-init-23.1-150400.7.7.src.rpm) altering this behavior.

That being said, there is no GATEWAY directive on your icfg files, what makes me think that cloud-init does not define any default gateway if not specified by the network config from openstack. But I did not dig into it.

**Comment by dermotbradley** [comment]
> That being said, there is no GATEWAY directive on your icfg files, what makes me think that cloud-init does not define any default gateway if not specified by the network config from openstack. But I did not dig into it.

As you will see from my earlier comment where I showed the cloud-init.log line where the network config obtained from Openstack is logged, Openstack provided **no** gateway information and therefore cloud-init cannot render any routes in sysconfig, and so this is not a cloud-init issue.

**Comment by aciba90** [comment]
Yes, @dermotbradley, those two lines did not add much value. The sentiment is that this is not  a cloud-init issue. It can be configured by defining the gateway info on OpenStack. Marking this as invalid. Thanks!

**Comment by TheRealFalcon** [comment]
Closing as this was marked invalid. Feel free to comment and/or reopen if you believe we have missed something.
