### ISSUE TITLE
cloud.cfg.tmpl sets default user to 'ubuntu' for debian

### ISSUE THREAD

**Issue by dermotbradley** [canonical/cloud-init#4267]
# Bug report

Looking at the following lines in config/cloud.cfg.tmpl:

https://github.com/canonical/cloud-init/blob/main/config/cloud.cfg.tmpl#L203-L206

when the variant is "debian" the default users' name is set to "ubuntu", not "debian".

This doesn't look correct!

Looking at the "git blame" this "if" statement seems to have been this way for 6 years.

## Environment details
- Cloud-init version: git main
- Operating System Distribution: Debian
- Cloud provider, platform or installer type: any

**Comment by TheRealFalcon** [comment]
Heh. Looks like Debian supplies [their own cloud.cfg](https://salsa.debian.org/cloud-team/cloud-init/-/blob/master/debian/cloud.cfg), but regardliess, you're right. We should remove this.

**Comment by dermotbradley** [comment]
> We should remove this.

It is taken care of as part of #4272

**Comment by dermotbradley** [comment]
> Heh. Looks like Debian supplies [their own cloud.cfg](https://salsa.debian.org/cloud-team/cloud-init/-/blob/master/debian/cloud.cfg), but regardliess, you're right. We should remove this.

@TheRealFalcon  I've made further changes to #4272 to align Debian config with the above referenced Debian cloud.cfg file.

**Comment by dermotbradley** [comment]
Fixed by #4272
