### ISSUE TITLE
Cannot import Current_RELEASE on non-Ubuntu systems

### ISSUE THREAD

**Issue by xiaoge1001** [canonical/cloud-init#4290]
# Bug report

In a non-Ubuntu system, an exception is thrown when the following code is executed:
pytest-3 -v tests/integration_tests/modules/test_combined.py::TestCombined::test_netplan_permissions

error info:
![图片](https://github.com/canonical/cloud-init/assets/103323735/bdc960cf-f0cd-4d1c-9a3d-921e5a581c17)

## Expected results:
Test case skipping

## Actual results:
ImportError

## Steps to reproduce the problem

on non-Ubuntu systems:
pytest-3 -v tests/integration_tests/modules/test_combined.py::TestCombined::test_netplan_permissions

## Environment details
- Cloud-init version: lastest
- Operating System Distribution: openEuler

**Comment by xiaoge1001** [comment]
We can catch the exception ValueError [here](https://github.com/canonical/cloud-init/blob/main/tests/integration_tests/releases.py#L74). Do not exit when an exception occurs, then "os, series, version = "unknown", None, None".

**Comment by TheRealFalcon** [comment]
Thanks for the bug report. Integration tests are current Ubuntu-only, but we'd like to be able to support other platforms. Either way we definitely shouldn't be tracing back there.

**Comment by TheRealFalcon** [comment]
Upon further investigation, this is expected behavior and not a bug.

See https://github.com/canonical/cloud-init/pull/4293#issuecomment-1661171333
