### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object in has_mount_opt()

### ISSUE THREAD

**Issue by xiaoge1001** [canonical/cloud-init#4321]
# Bug report
If the get_mount_info() function returns None, TypeError is triggered.
https://github.com/canonical/cloud-init/blame/main/cloudinit/util.py#L2785

## Steps to reproduce the problem
python3 -m pytest tests/unittests/

## Environment details
- Cloud-init version:23.2.2
- Operating System Distribution:openEuler

## cloud-init logs
Sorry, I can't log in to the problem environment. This is a CI environment and I can't get some useful information. But the analysis code does have this problem.

## Additional information
```
[  123s] path = '/var/tmp/cloud-init', opt = 'noexec'
[  123s] 
[  123s]     def has_mount_opt(path, opt: str) -> bool:
[  123s] >       *_, mnt_opts = get_mount_info(path, get_mnt_opts=True)
[  123s] E       TypeError: cannot unpack non-iterable NoneType object
```

**Comment by igalic** [comment]
what Version of cloud-init is this?
what OS is it running on?

**Comment by xiaoge1001** [comment]
> what Version of cloud-init is this? what OS is it running on?

Cloud-init version:23.2.2
Operating System Distribution:openEuler release 22.03 (LTS-SP1)

**Comment by xiaoge1001** [comment]
@igalic I'm sorry. The version information above is wrong. I tested two versions (21.4 and 23.2.2). 23.2.2 is fine, but 21.4+patch 919e22dc1d779f58f03dfd1cfde5ad9dc33a60d1 has problems.
However, analyzing the code shows that get_mount_info may indeed return None.

**Comment by xiaoge1001** [comment]
I can't log into the environment and it's not clear what triggered the p

**Comment by blackboxsw** [comment]
This feels a bit to me like unittests not mocking something it should have and through into the underlying test host/environment and which doesn't behave the way we expect. Is it possible to add your pytest logs or minimally the full failed log of the unit test names that are failing? That would help us narrow down which tests are problematic on openEuler

**Comment by xiaoge1001** [comment]
@igalic @blackboxsw 
In my CI environment, the /etc/fstab file exists but the size is 0.

**Comment by xiaoge1001** [comment]
I've learned that openeuler build environment is that there is no disk to mount in the chroot environment.

**Comment by igalic** [comment]
So my analysis here, https://github.com/canonical/cloud-init/pull/4322#discussion_r1286482441 was correct.
but then do is the code in #4322. (except maybe for the confusing log message;)

**Comment by xiaoge1001** [comment]
> except maybe for the confusing log message

I kind of understand what you're talking about. But in this case, should we throw an exception and leave it unhandled? Or should we ignore the exception and leave warning information in the log?

**Comment by igalic** [comment]
the warning level is fine.
I updated the PR with a comment on how to improve the log message.

**Comment by blackboxsw** [comment]
> @igalic @blackboxsw In my CI environment, the /etc/fstab file exists but the size is 0.
> 
> The /etc/mtab file exists and contains content. However, when I run the mount command, the system displays a message indicating that the file does not exist.
> 
> My CI environment is a container environment. These issues do not exist in my openEuler VM.

Given that this seems to only affect your CI environment and not an openEuler VM, This really feels like a unittest problem for sand-boxed environments, I'm really hesitant to make changes to the runtime code in cloudinit to support cases that we don't see in production environments and with a well defined understanding of the symptoms that require code changes.


I have also tested launching a container in LXD with openeuler and I'm not seeing issues with cloud-init due to runtime config.

```

 lxc launch images:openeuler/20.03 openeuler
lxc exec openeuler bash
yum install cloud-init
mkdir -p /var/lib/cloud/seed/nocloud/
cat > /var/lib/cloud/seed/nocloud/meta-data <<EOF
instance-id: myid1
local-hostname: I_WAS_HERE
EOF

cat > /var/lib/cloud/seed/nocloud/user-data <<EOF
#cloud-config 
ssh_import_id: [chad.smith]
EOF

cloud-init clean --logs --reboot

# no traces or type errors system setup and config on a contianer
get 


# get_mount_info("/") works well on the openeuler LXC container with an empty /etc/fstab

[root@openEchad ~]# cat /etc/fstab 

[root@openEchad ~]# python3 -c 'from cloudinit.util import get_mount_info; print(get_mount_info("/"))'
('default/containers/openeuler', 'zfs', '/')

```

Again, I'd label this problem as a unittest that is leaking out to a CI container system that doesn't represent a production VM/container of openeuler. Let's look to fix the leaks in unittests rather than trying to adapt the core logic around get_mount_info() unless we have a more firm cause of this problem.

**Comment by xiaoge1001** [comment]
@blackboxsw Thanks for your reply.

I just found that the /etc/fstab file was empty, but that's not necessarily the reason. I also found that when I run 'mount' command, the error message "mount: failed to read mtab: No such file or directory" is displayed. However, /etc/mtab exists and contains content.

**Comment by xiaoge1001** [comment]
I don't care about this issue now. Close the issue.
