### ISSUE TITLE
tox venv is not automatically updated when test-requirements.txt changes

### ISSUE THREAD

**Issue by rjschwei** [canonical/cloud-init#4341]
# Bug report
passlib was added to test-requirements.txt but we have nothing in the tox.ini file that automatically updates the test environment as such one ends up with 

```
tests/unittests/sources/test_azure.py:10: in <module>
    import passlib.hash
E   ModuleNotFoundError: No module named 'passlib'
```

There should be code in tox.init that updates the test venv when `test-requirements.txt` or `requirements.txt` changes.

## Environment details
- Cloud-init version: main
- Operating System Distribution: any
- Cloud provider, platform or installer type:

**Comment by TheRealFalcon** [comment]
Does running `tox -re` fix the problem? If so, that's just kind of a tox gotcha. If the requirements file changes, you need to rebuild your env.

**Comment by rjschwei** [comment]
It does fix the problem, so I learned that I don't know the tools as well as I should. 

That said, it makes me wonder if we cannot/should-not have a target `updatevenv` for example in `tox.ini` that would do this.

**Comment by TheRealFalcon** [comment]
> a target updatevenv for example in tox.ini that would do this

I think that'd be hard to do since creating a new rule would require a separate tox env, and tox tries to keep separation between the multiple environments. Since there's already a CLI option to do this, I'm not sure the effort would be worth it.

We could try to document this better, though we do have a few tox commands spread through the documentation, so I'm not sure the best place to put it.

**Comment by rjschwei** [comment]
Google wasn't all that helpful but I figured Id' throw this in here for consideration:

From https://stackoverflow.com/questions/73503092/how-to-update-tox-environments-when-requirements-txt-files-change

```
commands_pre = pip-sync requirements.txt
```
It appears to me that in the `py3` section we should be able to use this but of course we'd use `test-requirements.txt` and `requirements.txt`. Also would require that we have `pip-sync` in the venv

And then there is http://flummox-engineering.blogspot.com/2017/10/python-tox-virtual-environment-not-in-sync-with-requirements-txt.html which contains:

```
[tox]
tox_pip_extensions_ext_venv_update = true
```

but based on the text this doesn't sound like it handles changes to the requirements files automagically.

**Comment by holmanb** [comment]
I'm not sure automating this (and extra potential dependencies) is worth it, given how infrequently dependencies change.

**Comment by holmanb** [comment]
Since this is expected tox behavior that is resolved with the `-r` flag, and happens infrequently, automating tox cache update on requirements file is not planned at this time.

Thanks for the proposal.

**Comment by rjschwei** [comment]
Thanks, makes sense
