### ISSUE TITLE
[enhancement]: Jinja template error handling and user guidance in cloud-init

### ISSUE THREAD

**Issue by rajannpatel** [canonical/cloud-init#4360]
# Enhancement

There is difficulty when attempting to debug a Jinja template using the cloud-init command-line tools. The Jinja template in question is syntactically invalid, and when trying to debug it using the commands `cloud-init schema -i cloud-init.yaml` and `cloud-init query --fomat "$(cat cloud-init.yaml)"`, unhelpful and messy tracebacks are produced as a result of the bad Jinja syntax.

Expected Behavior:

The error handling and user guidance for such cases could be significantly improved within the cloud-init tool. When dealing with invalid Jinja template directives, the error messages and feedback provided by cloud-init should be more informative and user-friendly. Instead of just displaying traceback information, it would be beneficial if cloud-init could analyze the Jinja syntax error and offer a clearer and more targeted error message. This message should guide the user towards identifying the specific issues in their Jinja template.

Suggested Enhancement:

I propose that cloud-init should be enhanced to perform a more advanced analysis of Jinja syntax errors and provide user-friendly guidance. For instance, when encountering an invalid or misformatted Jinja template directive, cloud-init could generate an error message such as "Jinja template directive appears to be malformed or incorrectly formatted. Please check for missing or incorrect syntax near line X, column Y." This would provide users with a more precise indication of where the problem lies within their Jinja template.

Personal Experience:

In my case, I manually identified the issue in my Jinja template after a considerable amount of trial, error, and rubber ducking. The problem turned out to be related to trailing whitespace conditions (`% }`) that were not immediately apparent in the traceback. I believe that with improved error handling and guidance, users like me would be able to quickly identify and rectify such issues without extensive manual iteration.

By implementing this enhancement, cloud-init could save users valuable time and effort, making the debugging process more efficient and user-friendly.

**Comment by blackboxsw** [comment]
We may be able to invoke `jinja2.Environment.Parser.parse` on the content to provide a more informative error in logs instead of a traceback

**Comment by aciba90** [comment]
Being addressed here: https://github.com/canonical/cloud-init/pull/4510
