### ISSUE TITLE
Akamai missing from default list of DataSources

### ISSUE THREAD

**Issue by dermotbradley** [canonical/cloud-init#4362]
# Bug report

I assume that Akamai, a recently added DataSource should be listed in the default DS list here: https://github.com/canonical/cloud-init/blob/main/cloudinit/settings.py#L22

And also perhaps here? https://github.com/canonical/cloud-init/blob/main/cloudinit/apport.py#L29

## Environment details
- Cloud-init version: git main
- Operating System Distribution: all
- Cloud provider, platform or installer type:

**Comment by blackboxsw** [comment]
Agreed this needs fixing for 23.3

**Comment by aciba90** [comment]
Downstream Ubuntu branches need fixing too: https://cloudinit.readthedocs.io/en/latest/development/datasource_creation.html#enable-datasource-by-default-in-ubuntu-packaging-branches.
