### ISSUE TITLE
[docs]: disk setup

### ISSUE THREAD

**Issue by stringang** [canonical/cloud-init#4423]
# Documentation request
https://cloudinit.readthedocs.io/en/latest/reference/examples.html#disk-setup

I'm a beginner. I want to use cloud-init to automatically mount disks. I see in the documentation that device names are used. Do I need to know the device name in advance in order to mount it?

**Comment by blackboxsw** [comment]
@stringang this is probably more of a support question than an issue to file against cloud-init.

And yes, per the module docs you'd need to know your expected device paths beforehand. See the module reference docs for disk_setup for more info and additional examples: https://cloudinit.readthedocs.io/en/latest/reference/modules.html#disk-setup

It's probably best to either post questions like this either in our discourse channel or jump into our IRC channel per docs here 
https://cloudinit.readthedocs.io/en/latest/index.html#project-and-community
Closing so we can continue discussions in either of this channels.
