### ISSUE TITLE
[enhancement]: Modify net.generate_fallback_config() to configure IPv6 DHCP as well

### ISSUE THREAD

**Issue by ani-sinha** [canonical/cloud-init#4439]
# Enhancement

The following commit 
```
commit 7f674256c1426ffc419fd6b13e66a58754d94939
Author: Chad Smith <chad.smith@canonical.com>
Date:   Tue Aug 13 20:13:05 2019 +0000

    azure/net: generate_fallback_nic emits network v2 config instead of v1
    
    The function generate_fallback_config is used by Azure by default when
    not consuming IMDS configuration data. This function is also used by any
    datasource which does not implement it's own network config. This simple
    fallback configuration sets up dhcp on the most likely NIC. It will now
    emit network v2 instead of network v1.
    
    This is a step toward moving all components talking in v2 and allows us
    to avoid costly conversions between v1 and v2 for newer distributions
    which rely on netplan.
```
introduced the generate_fallback_config() to generate a fallback configuration for certain data sources like Azure in the default case (without IMDS). I wonder if this configuration can be enhanced to also generate dhcp6 configuration as well as dhcp4.

**Comment by TheRealFalcon** [comment]
That sounds like something we could do

**Comment by ani-sinha** [comment]
> That sounds like something we could do

Would this be enough? Sorry I am not very familier with this part of the code:

````
diff --git a/cloudinit/net/__init__.py b/cloudinit/net/__init__.py
index bf21633b..1357a852 100644
--- a/cloudinit/net/__init__.py
+++ b/cloudinit/net/__init__.py
@@ -571,7 +571,7 @@ def generate_fallback_config(config_driver=None):
         match = {
             "macaddress": read_sys_net_safe(target_name, "address").lower()
         }
-    cfg = {"dhcp4": True, "set-name": target_name, "match": match}
+    cfg = {"dhcp4": True, "dhcp6": True, "set-name": target_name, "match": match}
     if config_driver:
         driver = device_driver(target_name)
         if driver:
```

**Comment by TheRealFalcon** [comment]
Potentially, yes. We'd need to test to ensure it works as expected. `accept-ra` might also be relevant as an alternative to DHCP

**Comment by xiachen-rh** [comment]
I tested the change with "dhcp6":True, it can get ipv6 address on Azure when apply_network_config is false. 
+    cfg = {"dhcp4": True, "dhcp6": True, "set-name": target_name, "match": match}

but the change with "accept-ca":True, it can not get ipv6 address on Azure  when apply_network_config is false.  
+    cfg = {"dhcp4": True, "accept-ra": True, "set-name": target_name, "match": match} 

As the function generate_fallback_config may be called by others, what other scenarios should I do test? If you have any suggestion, let me know. thanks.

**Comment by ani-sinha** [comment]
Please also see the enhancement requested https://github.com/canonical/cloud-init/issues/4621 .
The resolution of this ticket depends on the resolution of the above ticket.
