### ISSUE TITLE
[enhancement]: Add shellcheck to CI

### ISSUE THREAD

**Issue by TheRealFalcon** [canonical/cloud-init#4453]
# Enhancement

https://github.com/koalaman/shellcheck

There are a couple of shell scripts that are very important to cloud-init. Therefore, adding shellcheck static analysis is a low effort automation tool to help catch code errors.

This is really only necessary for the [ds-identify](https://github.com/canonical/cloud-init/blob/main/tools/ds-identify) and [the systemd-generator](https://github.com/canonical/cloud-init/blob/main/systemd/cloud-init-generator.tmpl) script. We already have `# shellcheck disable` annotations in ds-identify, but we don't run shellcheck anywhere on build. It can likely be added to the [check_format](https://github.com/canonical/cloud-init/blob/main/.github/workflows/check_format.yml) script.

# Additional Details
The systemd-generator script is templated, so generating the script for the template is necessary prior to running. An example of generating the script from the template can be found [here](https://github.com/canonical/cloud-init/blob/dfe6170c222519634dacce2bd934d191e7d9957e/Makefile#L33). Please ask questions if this step causes trouble.

**Comment by itsaviral2609** [comment]
@TheRealFalcon I tried to generate but failing to generate the systemd-generator script when I ran it in my terminal.


![Screenshot from 2023-10-04 15-16-00](https://github.com/canonical/cloud-init/assets/96782675/667d7628-3649-4a00-97a9-90280712fe29)

**Comment by TheRealFalcon** [comment]
@itsaviral2609 Thanks for looking at this. It looks like you found a bug in one of our dev scripts. For what you're working on, I think we can exclude the systemd-generator script until we fix, and it can get added once we fix the template rendering.

**Comment by TheRealFalcon** [comment]
I raised https://github.com/canonical/cloud-init/issues/4487 for the issue found.

**Comment by holmanb** [comment]
Completed in https://github.com/canonical/cloud-init/pull/4488
