### ISSUE TITLE
[enhancement]: Specify proxy for module ansible for galaxy

### ISSUE THREAD

**Issue by zodd3131** [canonical/cloud-init#4454]
# Enhancement

If we run servers behind a proxy, ansible galaxy can't contact servers. adding a proxy option for ansible module could solve the problem.
Thanks!

**Comment by holmanb** [comment]
Thanks for this request. There was once a pull request proposed that implemented the desired feature, but it was [not merged in favor of a general solution](https://github.com/canonical/cloud-init/pull/1965/files) that would apply to all modules.

The effort of a general solution is larger than the original implementation but would prevent duplicating this effort across each module with special needs.

#### Possible Workaround
I haven't tested it, but it might be possible as a workaround to pass an environment variable to the cloud-init processes directly which might get inherited by the ansible-galaxy call by doing something like:
```
echo "DefaultEnvironment=http_proxy=http://proxy-server.local/" >> /etc/systemd/system.conf
```

But do note that you'll be passing this environment variable to all services that systemd starts, which may not be what you actually want and would be hard to audit the system-wide impact of.

**Comment by zodd3131** [comment]
Thank you for your reply. Unfortunately I can't make this workaround in my case, or It will be worse than download manually collections from a playbook prior to the execution of the main playbook.
We will wait for the general solution :)
Have a nice day!

**Comment by zodd3131** [comment]
issue can be closed.

**Comment by blackboxsw** [comment]
Will update this ticket when a general proxy solution is available in cloud-init.
