### ISSUE TITLE
[docs]: Route metric prop is optional in Netv2 docs but required in netplan docs

### ISSUE THREAD

**Issue by akutz** [canonical/cloud-init#4486]
# Documentation request
Currently the netplan documentation indicates that a `route` object's `metric` property is required (or at least not marked explicitly as optional, where other properties _are_): 

<img width="1088" alt="image" src="https://github.com/canonical/cloud-init/assets/101085/7e919e9e-aa51-401e-9596-087fa78187a0">

However, in the Cloud-Init networking v2 documentation, `metric` is explicitly marked optional:

<img width="1088" alt="image" src="https://github.com/canonical/cloud-init/assets/101085/d88ec296-b5f0-4842-85a5-6356d58ac6bf">

Can we please get some clarity on why there is this discrepancy? Is it optional in netplan? Does cloud-init just fill it in if it is missing? Thanks!

**Comment by TheRealFalcon** [comment]
Is it required in netplan? The netplan docs say `At least to must be specified`. That indicates that the remaining fields are optional. Cloud-init won't fill it in. It just isn't specified for the route. I don't know off the top of my head how that is handled, but if I run an `ip route`, the route representing only a `to` has no `src` or `metric` info on the line.

**Comment by akutz** [comment]
> Is it required in netplan? 

Other fields in the netplan documentation are explicitly marked optional. For example:

> port (scalar) – since 0.100
> UDP port to listen at or auto. Optional, defaults to auto.

> mark (scalar) – since 0.100
> Firewall mark for outgoing WireGuard packets from this interface, optional.

I concur that the wording you called out probably implies that fields other than `to` are optional. I guess it could just be more clear. Thanks!

**Comment by TheRealFalcon** [comment]
@akutz would you say this is more an issue with the netplan documentation then? If so, and you don't think we need anything in particular in cloud-init, I'll close this issue.

**Comment by TheRealFalcon** [comment]
I'll create an issue and link it here.

**Comment by TheRealFalcon** [comment]
Thanks @akutz , I opened https://bugs.launchpad.net/netplan/+bug/2038842 for this issue.
