### ISSUE TITLE
tmpl files not rendered by `render-cloudcfg`

### ISSUE THREAD

**Issue by TheRealFalcon** [canonical/cloud-init#4487]
Our Makefile has some rules that depend on `render-cloudcfg` being able to render generic `.tmpl` files. In this particular case, it is trying to render `systemd/cloud-init-generator.tmpl`:
```
render-template:
	$(PYTHON) ./tools/render-cloudcfg --variant=$(VARIANT) $(FILE) $(subst .tmpl,,$(FILE))
...
benchmark-generator: FILE=$(GENERATOR_F).tmpl
benchmark-generator: export ITER=$(NUM_ITER)
benchmark-generator: render-template
        $(BENCHMARK) $(GENERATOR_F)
```

However, the `render-cloudcfg` script eventually [attempts to load yaml](https://github.com/canonical/cloud-init/blob/main/cloudinit/templater.py/#L168). This works fine for rendered cloud-config, but it breaks for generic jinja templated scripts like `cloud-init-generator.tmpl`. 

The actual rendering code used on package build is [in setup.py](https://github.com/canonical/cloud-init/blob/main/setup.py/#L53). It looks like it may just be ignoring the error since the rendering portion works before hitting the error, and the script is exiting 0. We should create a new `render-template` script that can be used generically and fix the load yaml error.

**Comment by dermotbradley** [comment]
I assume this is the issue I'm seeing when I'm packaging up git main (but not seeing with 23.3): https://tpaste.us/papW

This appears to be due to parsing of systemd and FreeBSD init.d tmpl files.

What is strange is that I run: "python3 setup.py install --prefix=/usr --root="$pkgdir" --init-system=sysvinit_openrc"
 so shouldn't the "--init-system=sysvinit_openrc" option avoid **any** actions with Systemd and FreeBSD init.d files?

**Comment by TheRealFalcon** [comment]
Yes, that is strange. I wouldn't expect you to see systemd failures there...

**Comment by dermotbradley** [comment]
> Yes, that is strange. I wouldn't expect you to see systemd failures there...

Yeah I've run both 23.3 and git main packaging on the same environment (so same python version etc) and only see this output with git main.

I've diff'ed 23.3 and git main source and can't see anything that explains this.

**Comment by dermotbradley** [comment]
BTW I'm still seeing that "strange" output with git master when building/packaging for Alpine...
