### ISSUE TITLE
[enhancement]: add logrotate config file

### ISSUE THREAD

**Issue by laroche** [canonical/cloud-init#4509]
# Enhancement

Please consider adding a logrotate config file to your cloud-init source repository. Looking at bigger
files in /var/log/, cloud-init grows quite big logging files.

Please also see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926424 which ends
also into a merge request at https://salsa.debian.org/cloud-team/cloud-init/-/merge_requests/6.

best regards,

Florian La Roche

**Comment by itsaviral2609** [comment]
Hey @blackboxsw 
Can u guide me under which directory it will be added as logrotate file generally comes under /etc/logrotate.d.
Will add this if i get to know more on this :)
https://www.digitalocean.com/community/tutorials/how-to-manage-logfiles-with-logrotate-on-ubuntu-16-04

**Comment by aciba90** [comment]
Thanks for making cloud-init better.

For debian derivatives, I think it is enough to create a `cloud-init.logrotate` file under the `debian` folder in the Ubuntu downstream branches: [ubuntu/devel](https://github.com/canonical/cloud-init/tree/ubuntu/devel), [ubuntu/mantic](https://github.com/canonical/cloud-init/tree/ubuntu/mantic), [ubuntu/jammy](https://github.com/canonical/cloud-init/tree/ubuntu/jammy) and [ubuntu/focal](https://github.com/canonical/cloud-init/tree/ubuntu/focal). [dh_installlogrotate](https://manpages.debian.org/testing/debhelper/dh_installlogrotate.1.en.html) will handle the installation of the config file under `/etc/logrotate.d`

In addition to that, `cloud-init clean --logs` and `cloud-init collect-logs` have to be aware of this new behavior.

And optionally, we tend to document packaging changes under [packages/debian](https://github.com/canonical/cloud-init/tree/main/packages/debian) for packagers and testing.

**Comment by blackboxsw** [comment]
Thanks @aciba90 and correct, I think this is something we should look to implement. The `cloud-init clean --logs` and `collect-logs` determine their related log files from merged configuration in [cloudinit.util.get_config_logfiles](https://github.com/canonical/cloud-init/blob/main/cloudinit/util.py#L1739). It'd be good if we align `cloud-init collect-logs` and `cloud-init clean --logs` with the dynamic config-driven log file definitions so they both source `util.get_config_logfiles` if possible

**Comment by chifac08** [comment]
Related PR #4721

**Comment by aciba90** [comment]
https://github.com/canonical/cloud-init/pull/4721 added the support to collect and clean rotated logs, plus a reference log rotation config file.

What is missing is to add the logrotation config to [ubuntu/devel](https://github.com/canonical/cloud-init/tree/ubuntu/devel) under `debian/`, to add this to the devel series of Ubuntu.
