### ISSUE TITLE
What is a cloud-init boothook?

### ISSUE THREAD

**Issue by holmanb** [canonical/cloud-init#4542]
The current documentation doesn't show a user how to use it or what it does. It just has some cryptic hints about run frequency and implementation details of which directory the "hook" live in and doesn't even point to the examples[[1](https://github.com/canonical/cloud-init/blob/main/doc/examples/cloud-config-archive.txt)][[2](https://github.com/canonical/cloud-init/blob/main/doc/examples/cloud-config-archive-launch-index.txt)] of boothooks that exist in the source code (though I guess those are also pretty useless, frankly).

Trying to read [the docs](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#cloud-boothook), I find myself with more questions than answers:

> This content is boothook data. It is stored in a file under /var/lib/cloud and executed immediately. This is the earliest hook available.

Why do I need to know the directory (am I expected to / allowed to interact with `/var/lib/cloud`)? Which boot stage does this "immediately" belong to? How does it get executed (bash script, cloud-config, etc)? What does a hook do? Which other hooks are there?

> It is provided with the instance id in the environment variable INSTANCE_ID. This could be made use of to provide a ‘once-per-instance’ type of functionality.

The rest of this feature is left as an exercise to the user....

Honestly, this is pretty bad - we implement this for other user interfaces, why is this one half-baked? If that is what `tools/cloud-init-per` is for, then lets at least document that?

I think that many of the problems surrounding this feature is that there is no clear delineation between user and developer. The details exposed might be useful for a developer to know about, but a user trying to read docs and use it will be pretty frustrated.

I think we need to answer for the user, without knowing implementation details or reading code:

1. What problem does this feature solve?
2. What would make a user want to use this feature instead of a more documented user interface? 
3. How does a user use this feature?

**Comment by aciba90** [comment]
Tracking in https://warthogs.atlassian.net/browse/SC-1657.
