### ISSUE TITLE
[docs]: Document virt-install cloud-init integration 

### ISSUE THREAD

**Issue by holmanb** [canonical/cloud-init#4608]
# Documentation request
I don't think that this is documented, but it should be:

https://blog.wikichoon.com/2020/09/virt-install-cloud-init.html

**Comment by TheRealFalcon** [comment]
I know virt-install is a big project, but at the end of the day, this is just an external project that uses cloud-init, correct? Do you think it's worth having a section in our documentation with external projects using cloud-init? I'm thinking that list could get very long and convoluted, but it's probably worth a start.

**Comment by holmanb** [comment]
> I know virt-install is a big project, but at the end of the day, this is just an external project that uses cloud-init, correct?

While that statement is correct, I think it may help to reframe.

As a user, how is the `libvirt` family of projects any different than lxd or any other platform that supports cloud-init? We can add instructions describing how to run cloud-init locally using `virt-installer` for cloud-init testing / evaluation, just like we do with qemu, LXD, etc, etc.

I think that it is very different from projects such as Juju, snapd/core snaps, terraform, subiquity, etc, which wrap cloud-init to provide some specific functionality that has a different value proposition than cloud-init. Additionally it is different from multipass, which only allows a subset of cloud-init functionality. Libvirt is a platform that supports cloud-init just like lxd or lxc or qemu. My proposal is to add this to our "how to run locally" page. 

> Do you think it's worth having a section in our documentation with external projects using cloud-init?

No. Perhaps a product manager would want a marketing page displaying all of the different projects that use cloud-init, but I don't think that would add much value for a user, besides perhaps some authority / assurance on the use of the project.

**Comment by TheRealFalcon** [comment]
Thanks, I see your intention now. I agree, and I think it makes sense to call out various tools that make it most easy to interact with, test, and develop cloud-init.
