### ISSUE TITLE
Do something about TODO.rst

### ISSUE THREAD

**Issue by holmanb** [canonical/cloud-init#4623]
# Bug report
This file was last touched 9 years ago, and most of the content is probably irrelevant today. There _are_ efforts to improve the cloud-init codebase that could be documented, but if we document those and they go unchanged for another 9 years is that any better than just removing this file now?

Lets make a plan for this file or can it entirely.

**Comment by TheRealFalcon** [comment]
We should remove it. Github Issues is our upstream todo list.
