### ISSUE TITLE
[Aliyun] There should be no schema WARNING log if the userdata is empty

### ISSUE THREAD

**Issue by zhaohuijuan** [canonical/cloud-init#4632]
## Bug report
There is schema WARNING log if the userdata is empty on Aliyun, suggest to remove such WARNING log.
And the "#sudo  cloud-init schema --system" output is not suitable to report Error for the empty userdata file.

$ cat /var/log/cloud-init.log | grep -i WARNING
2023-11-28 14:28:07,681 - schema.py[WARNING]: Invalid cloud-config provided: Please run 'sudo cloud-init schema --system' to see the schema errors.

$ sudo cloud-init schema --system
Invalid cloud-config /var/lib/cloud/instances/i-2zehoojmes8rcmvxmeuu/cloud-config.txt
Error: Cloud config schema errors: format-l1.c1: File /var/lib/cloud/instances/i-2zehoojmes8rcmvxmeuu/cloud-config.txt needs to begin with "#cloud-config"

Error: Invalid cloud-config schema: user-data

## Steps to reproduce the problem
1. Deploy VM with cloud-init(no userdata) on Aliyun
2. Login VM and check the logs
$ cat /var/log/cloud-init.log | grep -i WARNING
2023-11-28 14:28:07,681 - schema.py[WARNING]: Invalid cloud-config provided: Please run 'sudo cloud-init schema --system' to see the schema errors.

$sudo cloud-init schema --system
Invalid cloud-config /var/lib/cloud/instances/i-2zehoojmes8rcmvxmeuu/cloud-config.txt
Error: Cloud config schema errors: format-l1.c1: File /var/lib/cloud/instances/i-2zehoojmes8rcmvxmeuu/cloud-config.txt needs to begin with "#cloud-config"

Error: Invalid cloud-config schema: user-data

$ sudo cat /var/lib/cloud/instances/i-2zehoojmes8rcmvxmeuu/cloud-config.txt
$sudo cloud-init query userdata

## Environment details
- Cloud-init version: cloud-init-23.1.1
- Operating System Distribution: RHEL
- Cloud provider, platform or installer type: Aliyun

## Additional info
No schema WARNING log in cloud-init.log on OpenStack if the userdata is empty, but the "# cloud-init schema --system" output is same with Aliyun

**Comment by xiachen-rh** [comment]
@zhaohuijuan this commit may fix the issue, we can test it
https://github.com/canonical/cloud-init/commit/d9436adae861d0691f3028e580d175cdd61eb39b

**Comment by blackboxsw** [comment]
Thanks @zhaohuijuan for filing this bug and making cloud-init better.  I can confirm that empty config on daily images no longer emits errors on empty cloud-config user-data.


````
root@i-4632:~# cloud-init schema --system
Found cloud-config data types: user-data, network-config

1. user-data at /var/lib/cloud/instances/9694fdc5-8c78-4f40-976d-cf6ba75f6dc0/cloud-config.txt:
Empty 'cloud-config' found at /var/lib/cloud/instances/9694fdc5-8c78-4f40-976d-cf6ba75f6dc0/cloud-config.txt. Nothing to validate.
````
I root@i-4632:~# cloud-init schema --system
Found cloud-config data types: user-data, network-config

1. user-data at /var/lib/cloud/instances/9694fdc5-8c78-4f40-976d-cf6ba75f6dc0/cloud-config.txt:
Empty 'cloud-config' found at /var/lib/cloud/instances/9694fdc5-8c78-4f40-976d-cf6ba75f6dc0/cloud-config.txt. Nothing to validate.
```
I can also confirm 23.1.1 tag shows this failure, and tip of main. 

The commit that fixed this is ff3beb3fdb8a81a9d116bdee5f8e69a067f63db4
It will be in our 23.4 release.

**Comment by blackboxsw** [comment]
Marked as fix commited at ff3beb3

**Comment by zhaohuijuan** [comment]
Thank you Chad for the quickly update and information, good to know it was fixed. I will verify it in 23.4 after it is released, thanks again.

**Comment by zhaohuijuan** [comment]
Tested this issue in the rebase 23.4, it is fixed.

# cloud-init schema --system
Found cloud-config data types: user-data, network-config

1. user-data at /var/lib/cloud/instances/i-2ze9dti9dfrz7nh2j7wp/cloud-config.txt:
Empty 'cloud-config' found at /var/lib/cloud/instances/i-2ze9dti9dfrz7nh2j7wp/cloud-config.txt. Nothing to validate.

2. network-config at /var/lib/cloud/instances/i-2ze9dti9dfrz7nh2j7wp/network-config.json:
Skipping network-config schema validation. No network schema for version: 2
