### ISSUE TITLE
[docs]: Document drop-in 3rd party modules

### ISSUE THREAD

**Issue by holmanb** [canonical/cloud-init#4649]
# Documentation request
Cloud-init provides code for drop-in 3rd party modules. These can be [custom mergers](https://cloudinit.readthedocs.io/en/latest/reference/merging.html#customisation), [custom handlers](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#part-handler), custom datasources, custom configuration modules, or [custom cleaners](https://github.com/canonical/cloud-init/pull/4761/files).

These are categorically different than typical user configuration. Users are expected to run commands and write configurations. This customization to cloud-init expect the user to write code, which lands them in a grey zone between user and developer - call them "super user" for now.

Currently only custom mergers and custom handlers are documented, and the documentation for those is intermingled with "normal user" documentation. This "super user" documentation is likely confusing alongside normal configuration documentation, and should perhaps be relocated somewhere different for clarity (and linked from "normal user" documentation).

I imagine a document structure like this:
```
doc/rtd/reference/custom_modules/index.rst
doc/rtd/reference/custom_modules/custom_datasource.rst
doc/rtd/reference/custom_modules/custom_configuration_module.rst
doc/rtd/reference/custom_modules/custom_mergers.rst
doc/rtd/reference/custom_modules/custom_formats.rst
doc/rtd/reference/custom_modules/custom_cleaners.rst
```

The index.rst page should discuss the merits, drawbacks, and strategies for using these interfaces. Each sub-page should describe the interface and provide a brief example.

**Comment by blackboxsw** [comment]
big +1 on separating those docs for "power users" with custom downstream image needs and behaviors. These scopres are atypical for most cloud-init users.

**Comment by aciba90** [comment]
Distros can also be dropped-in, but there is no documentation on how to create a new distro. Thus, I would propose to create a separate issue/s for documenting how to create a new distro and how to drop in a new distro.
