### ISSUE TITLE
[enhancement]: add support for doas instead of sudo for platforms where that is default

### ISSUE THREAD

**Issue by igalic** [canonical/cloud-init#4652]
# Enhancement

Currently we primarily support `sudo` for authorization.
Some of our code also makes the assumption that `sudo` is there when needed.

However, some platforms, notably OpenBSD, come with `doas` in their base-system.
That means we can get rid of another dependency.

## Stumbling stones

Note however, that `doas` is a little bit stricter.
Trying to run `tools/read-version` for instance under `doas` fails.
when re-running the underlying commands, we can see why:

```
meena@obsd74 ~/s/cloud-init (main)> doas git rev-parse --abbrev-ref HEAD
fatal: detected dubious ownership in repository at '/home/meena/src/cloud-init'
To add an exception for this directory, call:

        git config --global --add safe.directory /home/meena/src/cloud-init
meena@obsd74 ~/s/cloud-init (main) [128]> 
```

(n.b.: i have not yet found the underlying cause for this.)

**Comment by dermotbradley** [comment]
What doas support do you think is missing?

Some time ago I added doas support to cc_users_groups and also for cc_ssh_import_id to fallback to "doas" if "sudo" is missing. I'm running cloud-init fine on Alpine where doas is the default and I don't (typically) have sudo installed.

I haven't (yet) added doas support to byobu (as it is currently only for Debian & Ubuntu).

The only DataSource which makes use of sudo is OpenNebula and that looks simple to address to handle doas also.

There are various places in cloud-init where log entries say "Try sudo ......" that can be changed by those are only log messages. Likewise for docs.

Other than that there are a couple of sudo references in tools/read-dependencies, tools/mock-meta.py, tools/build-on-freebsd, tools/build-on-netbsd, tools/xkvm, and tools/build-on-openbsd which general look simple to address.

**Comment by igalic** [comment]
following @dermotbradley's comment i think it's safe to close this as completed
