### ISSUE TITLE
[Question] fetch network config from NoCloud web datasource without using DHCP.

### ISSUE THREAD

**Issue by m-a-rahal-os** [canonical/cloud-init#4701]
Hello,
I'm working on a cloud system with many VMs, I'm wondering if there's a way to apply network config at first boot while using a NoCloud network datasource (I'm passing 'ds=nocloud;s=http://<metadata-service-url>/<vm_uuid>/' as smbios serial).
The problem is that an IP address is needed to fetch from datasource, which means cloud-init must use DHCP to get first IP address, so it won't apply given network config first hand.
for context, I'm using libvirt to create virtual machines, and I'm aware that OpensStack uses ["ConfigDrive" datasource to solve this issue](https://docs.openstack.org/nova/latest/user/metadata.html#config-drives) (which is basically a CD-ROM containing config), but I'm curious if there's another way.

We have two possible solutions, but I'm not sure if they're correct:
1. changing the cloud image to have default network settings an IP address in same range/subnet as the Metadata service just so that cloud-init can fetch config data.
2. or create a template ISO image containing initial network config and mounted in all VMs 

Note that at the end of both cases, I want cloud-init to apply network config from metadata service (not the one set locally).

Thanks.

example of my cloud-init network_config:
version: 1
config:
  - type: physical
    name: enp1s0
    mac_address: "52:54:00:9d:3e:e1"
    subnets:
      - type: static
        address: 192.168.1.153/24
        gateway: 192.168.1.1
        dns_nameservers: ['1.1.1.1', '192.168.1.1'] 

example of my cloud-init logs: 
[cloud-init.log](https://github.com/canonical/cloud-init/files/13676956/cloud-init.log.txt)
[cloud-init-output.log](https://github.com/canonical/cloud-init/files/13676958/cloud-init-output.log.txt)

**Comment by holmanb** [comment]
> which means cloud-init must use DHCP to get first IP address, so it won't apply given network config first hand.

@m-a-rahal-os what do you mean by this?

After getting configuration via the ephemeral network (dhcp), cloud-init will render the configuration to disk so that the network daemon (NetworkManager, systemd-networkd, etc) will have configuration in place before it starts.

Can you use a dhcp server on the network that your VM is on to provide this IP?

**Comment by m-a-rahal-os** [comment]
Sorry it's a bit confusing... I think I'll simply use an ISO drive as data source instead. 
thanks
