### ISSUE TITLE
[docs]: Overhaul user data formats page

### ISSUE THREAD

**Issue by holmanb** [canonical/cloud-init#4739]
Cloud-init supports multiple formats, which are described on the [user data formats](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#user-data-formats) page.

This page has a few improvements that should be made:

1. Each format deserves a very brief example. This will make our format page more readable and allows skimming and reader intuition to fill in details faster than reading a wall of text.
2. This page contains an unrelated [kernel command line](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#kernel-command-line) section. This section does not describe a format, and should be relocated or (more likely) deleted.
3. This page contains an unrelated [how to disable user data](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#disabling-user-data) section. This section does not describe a format, and should be relocated.
4. This page contains a [how to write your own part-handler](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#part-handler) section. Future plans for this section have already been described in [another issue](https://github.com/canonical/cloud-init/issues/4649). tl;dr - this belongs elsewhere
5. Jinja templated user data is not documented on this page (it is best described on the [instance metadata](https://cloudinit.readthedocs.io/en/latest/explanation/instancedata.html#using-instance-data) page)
6. Currently these formats are not categorized, but could be categorized to make them easier to skim / grok by the reader (see the next section).

### Recommended format categorization

These formats fall into two categories, which I will call **base formats** and **meta-formats** for now.

**Base formats** are formats that allow the user to configure the instance via cloud-init. **Meta formats** are formats that modify or aggregate **base formats**.

**Base formats** include the following: [cloud config data](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#cloud-config-data), [user data scripts](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#user-data-script), [cloud-boothooks](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#cloud-boothook)

**Meta formats** include the following: [include files](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#include-file), [gzip compressed content](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#gzip-compressed-content), [mime archives](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#mime-multi-part-archive), jinja templates (need to be documented)

**Comment by TheRealFalcon** [comment]
The `User Data Scripts` section should additionally:
* Remove `euca-run-instances` reference
* Provide info on run frequency
* Include jinja templating in an example to show how that may be used in shell scripts
