### ISSUE TITLE
cloud-init not select `NetworkManager` renderer if `/etc/NetworkManager/NetworkManager.conf` absents

### ISSUE THREAD

**Issue by bin456789** [canonical/cloud-init#4741]
# Bug report

https://download.opensuse.org/tumbleweed/appliances/openSUSE-Tumbleweed-Minimal-VM.x86_64-Cloud.qcow2
This image have `NetworkManager` installed. No `networkd` installed.
But Cloud-init selects `networkd` renderer instead of `NetworkManager`

## Due to
cloud-init not select `NetworkManager` renderer if `/etc/NetworkManager/NetworkManager.conf` absents

## Fix
When select renderers
 - `NetworkManager`: Don't check if `/etc/NetworkManager/NetworkManager.conf` exists 
 - `networkd`: Check if `systemd-networkd` services exists

**Comment by TheRealFalcon** [comment]
Thanks for the bug report!
