### ISSUE TITLE
Add check on network interface name's length

### ISSUE THREAD

**Issue by TheRealFalcon** [canonical/cloud-init#4743]
Taken from https://bugs.launchpad.net/maas/+bug/2027975

When adding a VLAN on long network interfaces, Cloud-init will fail silently to add the sub-interfaces.

Deployed environment is :
* MAAS 3.3.4
* Server Dell R630 + Mellanox Connectx-5
* name of interfaces : enp130s0f0np0 / enp130s0f1np1
* add a VLAN like 100-4093

Cloud-Init will not display any error message but the VLAN interfaces will not be added after the deployment.
If trying to perform the operation manually, we are then greeted with the following error message.

```
ubuntu@R630:~$ sudo ip link add link enp130s0f0np0 name enp130s0f0np0.103 type vlan id 103
Error: argument "enp130s0f0np0.103" is wrong: "name" not a valid ifname
```

From Iproute2 and Kernel perspective, it is not possible to have interfaces with a name longer than 15 characters in total.

A quick workaround is simply to rename the network interface to something shorter.
Having a quick warning from MAAS would be nice to have to understand the origin of the issue.

Cloud-init should reject the names if it's told to create interfaces that don't have valid names

**Comment by blackboxsw** [comment]
Cloud-init already does "reject" these names, but it only emits warning logs, which only show up as non-zero exit code(2) on Ubuntu Noble and newer releases. Cloud-init status --long or --format=json on stable releases earlier than Noble will show the following warnings in logs and status output:
```
$ egrep -i 'warnerr' /var/log/cloud-init.log
2024-01-15 22:44:14,555 - stages.py[WARNING]: Failed to rename devices: Failed to apply network config names: [unknown] Error performing rename('enp5s0', 'eth01234567890123') for 02:00:00:35:ba:62, eth01234567890123: Unexpected error while running command.
Stderr: Error: argument "eth01234567890123" is wrong: "name" not a valid ifname


# also cloud-init status --format=json will emit this info in structured format
$  cloud-init status --format=json
...
  "recoverable_errors": {
    "WARNING": [
      "Failed to rename devices: Failed to apply network config names: [unknown] Error performing rename('enp5s0', 'eth01234567890123') for 02:00:00:35:ba:62, eth01234567890123: Unexpected error while running command.\nCommand: ['ip', 'link', 'set', 'enp5s0', 'name', 'eth01234567890123']\nExit code: 255\nReason: -\nStdout: \nStderr: Error: argument \"eth01234567890123\" is wrong: \"name\" not a valid ifname",
...
```


That said, we can add better schema validation for network config v1 to announce and annotate schema failures which will better announce that network-config version 1 doesn't ahere to a 15 character max.
