### ISSUE TITLE
alpine hosts template creates unexpected behavior for hostname -f command

### ISSUE THREAD

**Issue by parataku** [canonical/cloud-init#4771]
# Bug report
the layout of the current hosts.alpine.tmpl file results in unexpected behavior from the `hostname -f` command which should return the hostname + fqdn but only returns the hostname. 

It looks like this happens because of the changes in https://github.com/canonical/cloud-init/pull/1084.

## Steps to reproduce the problem
deploy a new vm based on the alpine 3.19 NoCloud image and provide both hostname and fqdn.
run `hostname` and `hostname -f` in the newly deployed machine, they should not return exactly the same output.
if you switch around hostname and fqdn in /etc/hosts it will work as expected.

## Environment details
- Cloud-init version: 23.4
- Operating System Distribution: alpine 3.19
- Cloud provider, platform or installer type: NoCloud

**Comment by TheRealFalcon** [comment]
@parataku , thanks for the bug report. I can reproduce the behavior.

Pinging @dermotbradley and @holmanb . We changed this in #1084, but according to `man 1 hostname`:
```
       The recommended method of setting the FQDN is to make the hostname be an alias for the fully  qualified  name  using
       /etc/hosts, DNS, or NIS. For example, if the hostname was "ursula", one might have a line in /etc/hosts which reads

              127.0.1.1    ursula.example.com ursula

       Technically:  The FQDN is the name getaddrinfo(3) returns for the host name returned by gethostname(2).  The DNS do‐
       main name is the part after the first dot.
```

It seems to me that the behavior prior to #1084 would be the expected behavior. What is the reasoning for the change?

**Comment by dermotbradley** [comment]
Hi. Yeah I obviously missed the implications of my previous PR.

I'm testing a change locally with both Busybox hostname and Coreutils hostname and will raise an PR shortly to address it.

@parataku I'll backport this also to the Alpine packages.

> What is the reasoning for the change?

It was to get "netstat" and "ss" output to use short form names (i.e. "localhost" rather than "localhost.localdomain".
