### ISSUE TITLE
Cloud-init Broken with jsonschema 4.21.0

### ISSUE THREAD

**Issue by holmanb** [canonical/cloud-init#4783]
# Bug report
I got CI working again in https://github.com/canonical/cloud-init/pull/4781, but we really should update our tests and make sure that the behavior that changed isn't something that actually breaks cloud-init.

## Steps to reproduce the problem
Run unittests with latest jsonschema.

**Comment by TheRealFalcon** [comment]
They changed some error messages and our tests were checking for specific error messages:
https://github.com/python-jsonschema/jsonschema/commit/8875c2ecb1094d8ba265a071d4c1ce9df1a94733
https://github.com/python-jsonschema/jsonschema/commit/a1d4cb3b94a83f209ebde1506a18b297a42b6219

Given that we'll have to support multiple versions of jsonschema across series, we either need to not check for a specific error message or check that we match either message.

**Comment by dermotbradley** [comment]
I'm now hitting this issue locally with my testing of Alpine cloud-init packaging (which I use for ongoing cloud-init development) as Alpine updated their py3-jsonschema  package to version 4.21.1 last week...

**Comment by dermotbradley** [comment]
@TheRealFalcon here's a diff of what I had to apply locally to get cloud-init tests passing with the latest py3-jsonschema: https://gist.github.com/dermotbradley/45f2987c9da4d2ad11e8374ba13f4062

I didn't raise a PR as this doesn't cover backwards-compatibility.
