### ISSUE TITLE
Schema error appears during boot regarding network v2 config with NoCloud

### ISSUE THREAD

**Issue by dermotbradley** [canonical/cloud-init#4814]
# Bug report

Whilst booting the console output shows:

```
2024-01-28 20:53:11,605 - schema.py[WARNING]: Invalid network-config provided: Please run 'sudo cloud-init schema --system' to see the schema errors.
```

running ``cloud-init schema --system`` shows:

```
Skipping network-config schema validation. No network schema for version: 2
```

The console-displayed message should not appear as the network-config provided is **not** invalid, the schema checker merely doesn't know how to validate it.

## Environment details
- Cloud-init version: git Main
- Operating System Distribution: Alpine Linux
- Cloud provider, platform or installer type: NoCloud with ISO

**Comment by blackboxsw** [comment]
Thanks for the bug @dermotbradley I'll put up a PR shortly to address this
