### ISSUE TITLE
[docs]: network config match on device path

### ISSUE THREAD

**Issue by ianb-mp** [canonical/cloud-init#4929]
# Documentation request

The documentation here https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v2.html#physical-devices-e-g-ethernet-wifi says:

> match: rules on desired properties, such as name/name pattern, MAC address, driver, or device paths.

But I can find nothing documented about matching on 'device paths'. Is it possible to match on e.g. pci device path `/sys/bus/pci/devices/0000:09:00.0` ?

**Comment by TheRealFalcon** [comment]
Thanks for the bug @ianb-mp . You are correct in that there are no device paths used. I will update the documentation.
