### ISSUE TITLE
nocloud-net not working in cloud-init >=23.4

### ISSUE THREAD

**Issue by rvandegrift** [canonical/cloud-init#4945]
# Bug report
I noticed that the nocloud-net datasource isn't working in 23.4.3.  If I set a seed via dmi, my http server never sees requests from cloud-init.  The same setup works fine with 23.3.1.  nocloud works fine in 23.4.3.

`git bisect` reports a commit first released in 23.4:
```
76b7b381497af9e4a6197606fd4d5fd5269b180b is the first bad commit
commit 76b7b381497af9e4a6197606fd4d5fd5269b180b
Author: Chris Patterson <cpatterson@microsoft.com>
Date:   Tue Sep 12 10:51:14 2023 -0400

    sources: do not override datasource detection if None is in list (#4426)

    Users with datasource_list = [Azure, None] started failing to boot
    properly outside of Azure with the changes to override datasource detection.

    If the fallback "None" is included in the datasource_list, do not treat
    the system as configured with a single datasource.

    If users want to force a single datasource regardless of detection,
    they can do so by removing None from the list.

    Signed-off-by: Chris Patterson <cpatterson@microsoft.com>

 cloudinit/sources/__init__.py | 5 +----
 1 file changed, 1 insertion(+), 4 deletions(-)
```

I wasn't able to test `main` with this reverted due to some test failures.  But the logs reveal that `override_ds_detect` is returning `False`.  In the working 23.3.1 case, the logs have this:
```
$ grep single cloud-init.log
2024-02-19 21:11:03,359 - __init__.py[DEBUG]: Machine is configured to run on single datasource DataSourceNoCloud [seed=None][dsmode=net].
2024-02-19 21:11:05,392 - __init__.py[DEBUG]: Machine is configured to run on single datasource DataSourceNoCloudNet [seed=None][dsmode=net].
```
But it's gone in 23.4.3.

## Steps to reproduce the problem
1. Start a webserver to serve a seed, nothing specific is required
2. Boot a qemu vm pointing to that server: `-smbios type=1,serial=ds='nocloud;s=http://10.0.2.2:8000/'` (`nocloud` vs `nocloud-net` makes no difference)
3. no requests are seen on the webserver, cloud-init uses `DataSourceNone`

## Environment details
- Cloud-init version: 23.4.3, current main (`89ebcc394`)
- Operating System Distribution: debian sid
- Cloud provider, platform or installer type: qemu

## cloud-init logs
logs from current main are attached.

[cloud-init-89ebcc394-logs.tar.gz](https://github.com/canonical/cloud-init/files/14382391/cloud-init-89ebcc394-logs.tar.gz)

**Comment by holmanb** [comment]
@rvandegrift  It looks like in cloud-init prior to 76b7b381497af9e, ds-identify's exact match forced the datasource, but after 76b7b381497af9e the kernel commandline match (not dmi) was how cloud-init's Python code was providing a positive match against NoCloud. I believe that one would have seen "Machine is configured by the kernel commandline to run on single datasource" after 76b7b381497af9e, but it still would have selected NoCloud.

The breaking behavior was actually introduced in the following commit, which was required to fix a collision with the kernel commandline argument `max_bonds=`.

```diff
commit d45beaa88e66b43f367b04157abb514b3e762c39
Author: Gilbert Gilb's <gilbsgilbs@users.noreply.github.com>
Date:   Thu Feb 1 22:47:42 2024 +0100

    fix(source): fix argument boundaries when parsing cmdline (#4825)

    When the command-line includes an argument that contains `ds=`, the rest
    of the argument is always interpreted as a datasource, regardless of
    wether the argument is `ds` or just the suffix of another argument.
    While this doesn't cause issues in a majority of cases, it starts
    conflicting with other arguments that also include `ds=` but do not
    refer to a cloud-init datasource. For instance, setting
    `bonding.max_bonds=0` in the command-line (which is a real-world
    use-case) conflicts with the current implementation.

    To fix this issue, this commit ensures that `ds`, `ci.ds` and
    `ci.datasource` arguments are either at the very beginning of the
    command-line, or just before a whitespace, so that we don't match
    another argument.

diff --git a/cloudinit/sources/__init__.py b/cloudinit/sources/__init__.py
index fb2498ae9..90edbae95 100644
--- a/cloudinit/sources/__init__.py
+++ b/cloudinit/sources/__init__.py
@@ -1191,9 +1191,9 @@ def parse_cmdline() -> str:
     Passing by command line overrides runtime datasource detection
     """
     cmdline = util.get_cmdline()
-    ds_parse_0 = re.search(r"ds=([^\s;]+)", cmdline)
-    ds_parse_1 = re.search(r"ci\.ds=([^\s;]+)", cmdline)
-    ds_parse_2 = re.search(r"ci\.datasource=([^\s;]+)", cmdline)
+    ds_parse_0 = re.search(r"(?:^|\s)ds=([^\s;]+)", cmdline)
+    ds_parse_1 = re.search(r"(?:^|\s)ci\.ds=([^\s;]+)", cmdline)
+    ds_parse_2 = re.search(r"(?:^|\s)ci\.datasource=([^\s;]+)", cmdline)
     ds = ds_parse_0 or ds_parse_1 or ds_parse_2
     deprecated = ds_parse_1 or ds_parse_2
     if deprecated:
diff --git a/tests/unittests/sources/test___init__.py b/tests/unittests/sources/test___init__.py
index 55c561d3c..f33d00103 100644
--- a/tests/unittests/sources/test___init__.py
+++ b/tests/unittests/sources/test___init__.py
@@ -17,6 +17,7 @@ openstack_ds_name = ds.DataSourceOpenStack.dsname.lower()
         ("aosiejfoij ci.ds=OpenStack faljskebflk", openstack_ds_name),
         ("ci.ds=OpenStack;", openstack_ds_name),
         ("ci.ds=openstack;", openstack_ds_name),
+        ("notci.ds=somecloud ci.ds=openstack", openstack_ds_name),
         # test ci.datasource=
         ("aosiejfoij ci.datasource=OpenStack ", openstack_ds_name),
         ("ci.datasource=OpenStack", openstack_ds_name),
@@ -24,6 +25,7 @@ openstack_ds_name = ds.DataSourceOpenStack.dsname.lower()
         ("aosiejfoij ci.datasource=OpenStack faljskebflk", openstack_ds_name),
         ("ci.datasource=OpenStack;", openstack_ds_name),
         ("ci.datasource=openstack;", openstack_ds_name),
+        ("notci.datasource=0 ci.datasource=nocloud", "nocloud"),
         # weird whitespace
         ("ci.datasource=OpenStack\n", openstack_ds_name),
         ("ci.datasource=OpenStack\t", openstack_ds_name),
@@ -35,6 +37,11 @@ openstack_ds_name = ds.DataSourceOpenStack.dsname.lower()
         ("ci.ds=OpenStack\v", openstack_ds_name),
         ("ci.ds=nocloud-net\v", "nocloud-net"),
         ("ci.datasource=nocloud\v", "nocloud"),
+        # test ds=
+        ("ds=nocloud-net", "nocloud-net"),
+        ("foo ds=nocloud-net bar", "nocloud-net"),
+        ("bonding.max_bonds=0", ""),
+        ("foo bonding.max_bonds=0 ds=nocloud-net bar", "nocloud-net"),
     ),
 )
 def test_ds_detect_kernel_commandline(m_cmdline, expected_ds):
diff --git a/tools/.github-cla-signers b/tools/.github-cla-signers
index 9e5735405..e0840d359 100644
--- a/tools/.github-cla-signers
+++ b/tools/.github-cla-signers
@@ -61,6 +61,7 @@ frantisekz
 GabrielNagy
 garzdin
 giggsoff
+gilbsgilbs
 glyg
 hamalq
 holmanb
```

**Comment by thannaske** [comment]
I'm also affected by the issue. Suddenly installations with cloud-init are failing with the following error:

```
DataSourceNoCloud.py[DEBUG]: See from http://my-cloud-init-url/ not supported by DataSourceNoCloud [seed=None][dsmode=net]
```

The serial is defined as following:
```
  <sysinfo type='smbios'>
    <system>
      <entry name='serial'>ds=nocloud-net;s=http://my-cloud-init-url/cloud-init/</entry>
    </system>
  </sysinfo>
```

**Comment by thannaske** [comment]
I can also confirm that downgrading the cloud-init package to 22.1-4 resolves the issue. This is really a deal breaker. That bug affects literally all cloud-init contextualisations I do.

**Comment by thannaske** [comment]
Appreciate your efforts, thank you. Unfortunately, the `-append` workaround isn't really feasible for us right now because it would affect a (very) large number of servers with hundreds of different operating systems and kernel version combinations.

We for now can only hope that the nocloud DMI/serial functionality is working again, soon. We may look into providing our own Datasource to eliminate the reliance on the generic datasource once and for all; until now we just didn't see the use case for developing one.

**Comment by holmanb** [comment]
> We for now can only hope that the nocloud DMI/serial functionality is working again, soon.

We will keep adding updates to this issue.

> We may look into providing our own Datasource to eliminate the reliance on the generic datasource once and for all; until now we just didn't see the use case for developing one.

Sounds good

Also, if testing cloud-init's proposed releases would be of value to you, that can be accomplished on test systems by enabling the `-proposed` repository from Ubuntu main and updating cloud-init. If a release is queued (like this fix will be soon), then your instance will get an updated cloud-init.  Early testing feedback is always welcome.

**Comment by blackboxsw** [comment]
The fix for this issue was resolved in the https://github.com/canonical/cloud-init/pull/4949 which landed in https://github.com/canonical/cloud-init/commit/66b5ce9d5f94c0c6625972fdfdca3796d365b069 and released as cloud-init version [23.4.4](https://github.com/canonical/cloud-init/releases/tag/23.4.4) . It is currently uploaded to the `-proposed` pocket for verification in Ubuntu Focal, Jammy and Mantic (and has already been uploaded to Ubuntu Noble). Expectation is that this will release within the next week to Ubuntu cloud-images.

**Comment by OnitiFR** [comment]
For anyone out there interested: the current (20240301) clould images use cloud-init 23.4.4 and now boots correctly!

Thanks to everyone involved in this fix! ❤️

**Comment by holmanb** [comment]
> For anyone out there interested: the current (20240301) clould images use cloud-init 23.4.4 and now boots correctly!
> 
> Thanks to everyone involved in this fix! ❤️

fyi @thannaske @rvandegrift
