### ISSUE TITLE
test_net test fail in the calico network env

### ISSUE THREAD

**Issue by xiaoge1001** [canonical/cloud-init#4973]
# Bug report
RuntimeError: duplicate mac found! both 'calixxx' and 'caliyyy' have mac 'ee:ee:ee:ee:ee:ee'.

## Steps to reproduce the problem

pytest tests/unittests/test_net.py
 
## Environment details
- Cloud-init version:23.4.1
- Operating System Distribution:openeuler

## cloud-init logs

```
2024-02-27 10:05:36                 msg = "duplicate mac found! both '%s' and '%s' have mac '%s'." % (
2024-02-27 10:05:36                     name,
2024-02-27 10:05:36                     ret[mac],
2024-02-27 10:05:36                     mac,
2024-02-27 10:05:36                 )
2024-02-27 10:05:36 >               raise RuntimeError(msg)
2024-02-27 10:05:36 E               RuntimeError: duplicate mac found! both 'caliaadab05bca1' and 'cali7a099f8b737' have mac 'ee:ee:ee:ee:ee:ee'.
2024-02-27 10:05:36 
2024-02-27 10:05:36 cloudinit/net/__init__.py:987: RuntimeError
```

**Comment by xiaoge1001** [comment]
I plan to use the following fix (verified to work), but don't know if it's correct.
fix patch: https://gitee.com/tong_1001/cloud-init/blob/master/Ignoring-duplicate-macs-for-calico-network.patch

**Comment by catmsred** [comment]
Thank you for reporting this bug!  23.4.1 has been superceded by 23.4.4 -- are you able to reproduce this issue in 23.4.4 as well?

**Comment by TheRealFalcon** [comment]
> pytest tests/unittests/test_net.py

`test_net.py` contains 223 tests. Can you provide the exact test or tests that failed?

**Comment by xiaoge1001** [comment]
> > pytest tests/unittests/test_net.py
> 
> `test_net.py` contains 223 tests. Can you provide the exact test or tests that failed?

cloud-init-23.4.1:
https://gitee.com/src-openeuler/cloud-init/issues/I93ZJT?from=project-issue    （See the attachment.）

**Comment by xiaoge1001** [comment]
I will use the latest version for the past two days to test it as well.

**Comment by blackboxsw** [comment]
@xiaoge1001 I expect https://github.com/canonical/cloud-init/pull/5012 may solve the build issues you are seeing. If you get a chance to test #5012 in your environment it will help give us a signal as to whether this resolves the issue you filed.

**Comment by xiaoge1001** [comment]
> @xiaoge1001 I expect #5012 may solve the build issues you are seeing. If you get a chance to test #5012 in your environment it will help give us a signal as to whether this resolves the issue you filed.

Thank you very much. I have tested the latest code and this issue have solved.
