### ISSUE TITLE
OpenBSD: Cloud-init not applying changes after the initial first boot

### ISSUE THREAD

**Issue by CodeBleu** [canonical/cloud-init#5033]
# Bug report
Attempting to change host name or password from Cloudstack, does not work.

## Steps to reproduce the problem

1. Clone cloud-init using `git clone https://github.com/canonical/cloud-init.git`
2. Navigate to the cloud-init directory using `cd cloud-init/`
3. Using `./tools/build-on-openbsd` install the tools within the cloud-init directory
4. reboot, and the initial hostname, password..etc is pulled from Cloudstack and works
5. Change hostname, password...etc in Cloudstack ( server reboots )
6. Still has previous information and does not update

## Temp solution
Add the following to `/etc/rc.local` and reboot.  All subsequent changes will work

- rm -f /run/.instance-id
- rm -f /run/instance-data*

## Environment details
- Cloud-init version: 23.4.4
- Operating System Distribution: OpenBSD 7.4
- Cloud provider, platform or installer type: CloudStack

## cloud-init logs

[cloud-init.tar.gz](https://github.com/canonical/cloud-init/files/14539977/cloud-init.tar.gz)

**Comment by igalic** [comment]
shouldn't that stuff be in `/run/cloud-init/`?
(or after #4820 in `/var/run/cloud-init`)

So, seems suspicious that it's directly in `/run`

**Comment by hcartiaux** [comment]
I can't reproduce on my side, these files are now stored in `/var/run/cloud-init`, this has probably been solved by #4820 like @igalic said.

**Comment by holmanb** [comment]
Closing, this was resolved in #4820.
