### ISSUE TITLE
[Question] The change in 23.4 for the config.0.subnets.1.routes.0.network in schema-network-config-v1.json

### ISSUE THREAD

**Issue by zhaohuijuan** [canonical/cloud-init#5051]
# Bug report
There is a schema check change after upgrade to cloud-init-23.4,  config.0.subnets.1.routes.0.network in schema-network-config-v1.json.

With this change, for the config on OpenStack:
     "routes": [
      {
       "gateway": "2620:1:0:1::1",
       "netmask": "::",
       "network": "::"
      }

It will report recoverable errors:
$ sudo cloud-init status --long
status: done
extended_status: degraded done
boot_status_code: enabled-by-generator
last_update: Tue, 12 Mar 2024 01:52:49 +0000
detail:
DataSourceOpenStackLocal [net,ver=2]
errors: []
recoverable_errors:
DEPRECATED:
	- Deprecated cloud-config provided: config.0.subnets.1.routes.0.network: IPv4 network address with CIDR netmask notation or IPv6 with prefix length. Alias for ``destination`` and only read when ``destination`` key is absent. Deprecated in version 23.3. Use ``destination`` instead.

Checked the schema-network-config-v1.json:
        "network": {
          "type": "string",
          "description": "IPv4 network address with CIDR netmask notation or IPv6 with prefix length. Alias for ``destination`` and only read when ``destination`` key is absent.",
          "deprecated": true,
          "deprecated_version": "23.3",
          "deprecated_description": "Use ``destination`` instead."
        },

My question is why the 'network' in the routes was deprecated since 23.3, is there any requirement? 
As our OpenStack ENV still uses the 'network' to config routes, but it reports warning/recoverable_errors after upgrade to 23.4.

Is this change comes from https://github.com/canonical/cloud-init/pull/4482?

## Environment details
- Cloud-init version:
- Operating System Distribution:
- Cloud provider, platform or installer type:

**Comment by TheRealFalcon** [comment]
> Is this change comes from https://github.com/canonical/cloud-init/pull/4482?

Yes, that is the PR that generates the warning.

> My question is why the 'network' in the routes was deprecated since 23.3, is there any requirement?

It is deprecated because it has gone undocumented and does the exact same thing as using the `destination` key. There is no reason to keep two keys to do the same thing, so we opted to deprecate it. It won't be removed anytime soon, but the warning allows people to plan for its eventual removal.

**Comment by zhaohuijuan** [comment]
ok, got it, thanks @TheRealFalcon for the reply and explanation. 
Then I will report an OpenStack issue  to check if they could modify 'network' as 'destination' to align with cloud-init change.

**Comment by TheRealFalcon** [comment]
@zhaohuijuan , it looks like we removed this key a bit too hastily. Given that this is something that cloud-init translates from Openstack's network_data.json, we can continue to support it moving forward. We'll include it in our upcoming 24.1.2 release.

**Comment by zhaohuijuan** [comment]
Thanks @TheRealFalcon for the quickly update and fix.
