### ISSUE TITLE
Kubernetes example

### ISSUE THREAD

**Issue by JCzz** [canonical/cloud-init#5096]
Hi

It could be very nice with a cloud-init kubernetes example.

Thanks

**Comment by aciba90** [comment]
Thanks, @JCzz, for reporting this. Could you please elaborate on what exactly would you like documented about cloud-init and kubernetes?

**Comment by JCzz** [comment]
Just som general cloud-init example... no worries, I have found a terraform that will do the job. 
Great job with multipass. 
Regards
