### ISSUE TITLE
[docs]: link expanation:configuration#base-configuration with reference:base_config_reference

### ISSUE THREAD

**Issue by aciba90** [canonical/cloud-init#5137]
# Documentation request

Link https://cloudinit.readthedocs.io/en/latest/explanation/configuration.html#base-configuration and https://cloudinit.readthedocs.io/en/latest/reference/base_config_reference.html to better guide doc consumers.

---
*Reported from: https://cloudinit.readthedocs.io/en/latest/explanation/configuration.html*

**Comment by holmanb** [comment]
@aciba90 it looks like this is already linked, is there anything left to do here?

**Comment by aciba90** [comment]
Nope, closing!
