### ISSUE TITLE
Remove DataSourceNone warning in cc_final_message 

### ISSUE THREAD

**Issue by TheRealFalcon** [canonical/cloud-init#5192]
# Bug report
In the past, `DataSourceNone` was used purely as a fallback for when a primary datasource failed. However, `DataSourceNone` can be a datasource in an of itself and preferrable to `NoCloud` if all configuration is baked into the image. Because of this, it no longer makes sense to issue a warning in cc_final_message if None was expected. If there is defined userdata/metadata under the datasource definition in /etc/cloud or `DataSourceNone` is the only entry in the `datasource_list`, we should not warn that `DataSourceNone` was used.

**Comment by Meulengracht** [comment]
We use data source [None] when testing Ubuntu Core, and I believe Certification team is too. The warning it produces to use this causes snapd to handle `cloud-init status` as an error, even when it actually produces the output `status: done`.

It seems like this is a new thing with the Noble build, on Jammy this seems a non issue
