### ISSUE TITLE
version19.4 使用kubevirt插件创建VM，yaml配置指定userdata，runcmd指令，没有执行，只有bootcmd执行了

### ISSUE THREAD

**Issue by zhenliangliang** [canonical/cloud-init#5196]
# Bug report

## Environment details
- Cloud-init version:
- Operating System Distribution:
- Cloud provider, platform or installer type:

**Comment by igalic** [comment]
it's hard to say why that is happening without a log. please give https://cloudinit.readthedocs.io/en/latest/howto/bugs.html a read.

**Comment by zhenliangliang** [comment]
> it's hard to say why that is happening without a log. please give https://cloudinit.readthedocs.io/en/latest/howto/bugs.html a read.

thank you! My purpose is to use the kubevirt plug-in to create a VM instance and then run some initialization commands, which involve file downloads and require a network connection. Therefore, I use runcmd in the config phase of cloud-init, but this command only has the first one. It will take effect after the first startup. Are there other ways to meet my scenario?

**Comment by holmanb** [comment]
@zhenliangliang This isn't the right channel for a support request. Support requests are best directed to the IRC channel (#cloud-init on Libera) or [the mailing list](https://launchpad.net/~cloud-init).

> Therefore, I use runcmd in the config phase of cloud-init, but this command only has the first one

Cloud-init is capable of running multiple commands in runcmd and is capable of doing initialization commands and file downloads after the network is available. Please be sure to add more context to your question when you ask (on the mailing list or IRC).
