### ISSUE TITLE
[docs]: missing redirect (en/latest/topics/availability.html)

### ISSUE THREAD

**Issue by AjBreidenbach** [canonical/cloud-init#5284]
# Documentation request
https://cloudinit.readthedocs.io/en/latest/topics/availability.html
Appears to have moved to
https://docs.cloud-init.io/en/latest/reference/availability.html

**Comment by blackboxsw** [comment]
Thank you for filing the bug @AjBreidenbach and making cloud-init better. We have updated a number of missed URL redirects. One of which is this availability page link.

**Comment by blackboxsw** [comment]
Configuration and redirects have been added in our RTD config. The link https://cloudinit.readthedocs.io/en/latest/topics/availability.html automatically forwards to the right upstream doc url.
