### ISSUE TITLE
Typo in logrotate config

### ISSUE THREAD

**Issue by abuibrahim** [canonical/cloud-init#5316]
https://github.com/canonical/cloud-init/blob/739c5f63c41fe08f72c9138f300fe117f63d3403/packages/debian/cloud-init.logrotate#L9

should have been `delaycompress`

**Comment by blackboxsw** [comment]
Thank you for filing this bug and making cloud-init better!
Fix up for review https://github.com/canonical/cloud-init/pull/5317
