### ISSUE TITLE
Cloud-init aborted on WSL

### ISSUE THREAD

**Issue by thielj** [canonical/cloud-init#5331]
# Bug report

I have previously reported this against WSL as I think this is an issue that's not caused by cloud-init itself, so I'm linking this here for reference only.

## Summary

When initializing Ubuntu-2404 in WSL, some kind of 'watchdog' kicks in after 10000ms and aborts cloud-init about 15s later, usually during the final phase. 

Cloud-init works for quick tasks, but when adding multiple packages, apt-get is simply terminated and not re-run later.

For details and logs, see https://github.com/microsoft/WSL/issues/11602

**Comment by blackboxsw** [comment]
Thank you for filing this bug and improving cloud-init.
CC: @CarlosNihelton in case there is a default wsl.conf setting we may need to set up if we see "complex" user-data.

**Comment by CarlosNihelton** [comment]
Very interesting report. My initial thoughts are that we need to deal with the WSL side of the things first, as there is no logic in cloud-init itself that would prevent that shutdown per my understanding after vewing the logs reported in the other bug report.

Thanks for the good insights @thielj . I'll investigate this further.

**Comment by CarlosNihelton** [comment]
What's been your experience with the two-step installation workflow described here:
 https://canonical-ubuntu-wsl.readthedocs-hosted.com/en/latest/tutorials/cloud-init/ ?

Have you been as impacted by the timeouts and surprising behaviors of WSL?

**Comment by CarlosNihelton** [comment]
> Are these even in the official WSL docs?

Cloud-init support is not an upstream WSL feature, but rather specific to Ubuntu (by now, at least, as nothing in the implementation prevents other distros to benefit from it), thus those are Ubuntu docs, rather than MS docs.

**Comment by a-dubs** [comment]
@CarlosNihelton Setting this to bug: external since the issue does not seem to lie with cloud-init.

**Comment by CarlosNihelton** [comment]
> It might help to (a) emphasize that running `ubuntu2404.exe run cloud-init status --wait` _immediately_ after installation has completed is not just about watching cloud-init do its job - it's rather existential for cloud-init to complete anything more than a quick useradd. Even an idle shell would be enough for the WSL 10000ms watchdog timer to consider the distro to be in use.
> 


I did an interesting investigation on this topic and got the conclusion that adding such a call into the Ubuntu distro launcher executable itself is enough (if the particular distro instance being launched had cloud-init ofc). Users won't have to worry about this pretty soon.

**Comment by CarlosNihelton** [comment]
Hey @thielj you might like the latest release of Ubuntu 24.04 LTS. The distro launcher now "protects" cloud-init runs, so it's use is more transparent. We also updated the documentation (which is now in a more discoverable place).

https://documentation.ubuntu.com/wsl/en/latest/tutorials/cloud-init/
