### ISSUE TITLE
[docs]: Boot stage picture

### ISSUE THREAD

**Issue by blackboxsw** [canonical/cloud-init#5334]
# Documentation request

Please provide a simple diagram/visual that shows boot stages -> related system units/services to give a quick overview of boot in
https://cloudinit.readthedocs.io/en/latest/explanation/boot.html#boot-stages

This will aid new users in understanding what "boot stages" are and how they relate to systemd or boot services related to cloud-init.

Additional wants:
 - when SSH or login is possible 
 - when network is configured
 - when IMDS accessed
 - horizontal diagram, simple and easy to glance at

**Comment by aciba90** [comment]
Tracking in https://warthogs.atlassian.net/browse/SC-1835.
