### ISSUE TITLE
Cloud config schema error: Additional properties are not allowed ('mac_address' was unexpected)

### ISSUE THREAD

**Issue by jcmoore3** [canonical/cloud-init#5364]
# Bug report
When using OpenStack with a network_data.json file which specifies a VLAN, there is a mismatch between the schemas for VLANs between OpenStack and cloudinit.

https://opendev.org/openstack/nova/src/branch/master/doc/api_schemas/network_data.json#L201
https://github.com/canonical/cloud-init/blob/main/cloudinit/config/schemas/schema-network-config-v1.json#L350

There should be a `mac_address` field in the cloudinit schema for VLANs so that when the `vlan_mac_address` address field (required) is translated from the OpenStack network_data.json file, it properly validates the schema:
https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/helpers/openstack.py#L703

## Steps to reproduce the problem
Create an OpenStack node with the following network_data.json:
```
{
  "links": [
    {
      "id": "ens1f0np0",
      "name": "ens1f0np0",
      "type": "phy",
      "ethernet_mac_address": "xx:xx:xx:xx:xx:00",
      "mtu": 9000
    },
    {
      "id": "ens1f1np1",
      "name": "ens1f1np1",
      "type": "phy",
      "ethernet_mac_address": "xx:xx:xx:xx:xx:01",
      "mtu": 9000
    },
    {
      "id": "bond0",
      "name": "bond0",
      "type": "bond",
      "bond_links": [
        "ens1f0np0", "ens1f1np1"
      ],
      "mtu": 9000,
      "ethernet_mac_address": "xx:xx:xx:xx:xx:00",
      "bond_mode": "802.3ad",
      "bond_xmit_hash_policy": "layer3+4",
      "bond_miimon": 100
    },
    {
      "id": "bond0.123",
      "name": "bond0.123",
      "type": "vlan",
      "vlan_link": "bond0",
      "vlan_id": 123,
      "vlan_mac_address": "xx:xx:xx:xx:xx:00"
    }
  ],
  "networks": [
    {
      "id": "publicnet-ipv4",
      "type": "ipv4",
      "link": "bond0.123",
      "ip_address": "x.x.x.x",
      "netmask": "255.255.255.0",
      "routes": [
        {
          "network": "0.0.0.0",
          "netmask": "0.0.0.0",
          "gateway": "x.x.x.1"
        }
      ],
      "network_id": "00000000-0000-0000-0000-000000000000"
    }
  ],
  "services": [
    {
      "type": "dns",
      "address": "1.1.1.1"
    }
  ]
}
``` 
Cloudinit will produce the following network-config.json:
```
{
 "config": [
  {
   "mac_address": "xx:xx:xx:xx:xx:00",
   "mtu": 9000,
   "name": "ens1f0np0",
   "subnets": [],
   "type": "physical"
  },
  {
   "mac_address": "xx:xx:xx:xx:xx:01",
   "mtu": 9000,
   "name": "ens1f1np1",
   "subnets": [],
   "type": "physical"
  },
  {
   "bond_interfaces": [
    "ens1f0np0",
    "ens1f1np1"
   ],
   "mac_address": "xx:xx:xx:xx:xx:00",
   "mtu": 9000,
   "name": "bond0",
   "params": {
    "bond-miimon": 100,
    "bond-mode": "802.3ad",
    "bond-xmit_hash_policy": "layer3+4"
   },
   "subnets": [],
   "type": "bond"
  },
  {
   "mac_address": "xx:xx:xx:xx:xx:00",
   "name": "bond0.123",
   "subnets": [
    {
     "address": "x.x.x.x",
     "ipv4": true,
     "netmask": "255.255.255.0",
     "routes": [
      {
       "gateway": "x.x.x.1",
       "netmask": "0.0.0.0",
       "network": "0.0.0.0"
      }
     ],
     "type": "static"
    }
   ],
   "type": "vlan",
   "vlan_id": 123,
   "vlan_link": "bond0"
  },
  {
   "address": "1.1.1.1",
   "type": "nameserver"
  }
 ],
 "version": 1
}
```
## Environment details
- Cloud-init version: 23.4-7.el9_4.0.1
- Operating System Distribution: Rocky 9
- Cloud provider, platform or installer type: OpenStack Caracal 2024.1

## cloud-init logs
```
Cloud-init v. 23.4-7.el9_4.0.1 running 'init-local' at Tue, 04 Jun 2024 15:22:46 +0000. Up 1370.68 seconds.
2024-06-04 15:22:46,686 - schema.py[WARNING]: Invalid network-config provided:
config.3: Additional properties are not allowed ('mac_address' was unexpected)
config.3: {'name': 'bond0.123', 'type': 'vlan', 'subnets': [{'type': 'static', 'netmask': '255.255.255.0', 'routes': [{'network': '0.0.0.0', 'netmask': '0.0.0.0', 'gateway': 'x.x.x.1'}], 'address': 'x.x.x.x', 'ipv4': True}], 'vlan_id': 123, 'mac_address': 'xx:xx:xx:xx:xx:00', 'vlan_link': 'bond0'} is not valid under any of the given schemas
```

**Comment by aciba90** [comment]
Hi, @jcmoore3. In this case, the schema is correct. Cloud-init's network config version 1 does not support `mac_address` as a property when `type == vlan`: https://docs.cloud-init.io/en/latest/reference/network-config-format-v1.html#vlan, so that property is ignored by cloud-init.

**Comment by aciba90** [comment]
This bug is invalid, unless support for that subkey (if it makes sense) is your request.

**Comment by aciba90** [comment]
@jcmoore3, thanks for clarifying the issue. I would say 1 is the most immediate thing to do and if support is required we could implement 2 and proper support for `mac_address` under net config v1.

**Comment by jcmoore3** [comment]
@aciba90 - I have updated the PR to remove parsing of the `vlan_mac_address` field for this specific case. With this change, the `vlan_mac_address` from OpenStack's `network_data.json` is still used to populate the `mac` field which is used elsewhere in cloudinit, but not output as a discrete field in `network-config.json`.
