### ISSUE TITLE
DataSourceCloudstack: typo in 23.4.x

### ISSUE THREAD

**Issue by benj-n** [canonical/cloud-init#5378]
# Bug report
23.4.x: 
Cloudstack DataSource cannot get the metadata server address from the dhcp lease files when not using the data-server dns record, nor networkd. 
The reason is obvious, there's a huge typo in the variable name at
https://github.com/canonical/cloud-init/blob/fe3893aaba07795e4d90f0bfbace74c32440fe24/cloudinit/sources/DataSourceCloudStack.py#L238C1-L240C1

The lines:
```
lease_file = dhcp.IscDhclient.parse_dhcp_server_from_lease_file(lease_file)
  if not latest_address:
    ...
```
Should read:
```
latest_address = dhcp.IscDhclient.parse_dhcp_server_from_lease_file(lease_file)
  if not latest_address:
    ...
```

## Steps to reproduce the problem
1/ Prepare a qcow2 template for any operating system using cloud-init 23.4.X and NetworkManager (namely the current EL8.10 and EL9.4 derivatives like Rocky Linux 8, Rocky Linux 9, AlmaLinux 8 or AlmaLinux9)
2/ Spin up a VM on Cloudstack (4.18) from the aforementioned template, in a Zone with security groups enabled, in a shared  network (so there's no data-server DNS record available).
3/ Observe cloud-init failing to fetch the metadata server address.

## Environment details
- Cloud-init version: 23.4.X
- Operating System Distribution: All current enterprise Linux derivatives (Rocky and Alma 8.10 and 9.4, probably RHEL too.)
- Cloud provider, platform or installer type: CloudstackDataSource

## cloud-init logs
(IP addresses have been redacted)
```
2024-06-06 09:02:35,684 - util.py[DEBUG]: Cloud-init v. 23.4-7.el9_4.0.1 running 'init' at Thu, 06 Jun 2024 09:02:35 +0000. Up 2919.84 seconds.
2024-06-06 09:02:35,688 - main.py[INFO]: PID [1002] started cloud-init.
(...)
2024-06-06 09:04:28,655 - DataSourceCloudStack.py[DEBUG]: DNS Entry data-server not found
2024-06-06 09:04:28,655 - dhcp.py[DEBUG]: Using /var/lib/NetworkManager lease directory
2024-06-06 09:04:28,655 - dhcp.py[DEBUG]: Found DHCP identifier x.y.z.129
2024-06-06 09:04:28,655 - DataSourceCloudStack.py[DEBUG]: No DHCP found, using default gateway
2024-06-06 09:04:28,656 - util.py[DEBUG]: Reading from /proc/net/route (quiet=False)
2024-06-06 09:04:28,656 - util.py[DEBUG]: Read 384 bytes from /proc/net/route
2024-06-06 09:04:28,656 - DataSourceCloudStack.py[DEBUG]: Found default route, gateway is x.y.z.254
```

**Comment by benj-n** [comment]
PR: https://github.com/canonical/cloud-init/pull/5379

**Comment by aciba90** [comment]
Hello, @benj-n, thanks 

This was fixed in https://github.com/canonical/cloud-init/commit/cb36bf38b823f811a3e938ccffc03d7d13190095 and included in cloud-init 24.1. 

Generally speaking, we only do hotfix releases for the latest version. Is it possible for you to upgrade to a newer version? Or propose https://github.com/canonical/cloud-init/commit/cb36bf38b823f811a3e938ccffc03d7d13190095 as a patch in EL ?

**Comment by benj-n** [comment]
I mentioned the https://github.com/canonical/cloud-init/commit/cb36bf38b823f811a3e938ccffc03d7d13190095 patch in the RedHat bug report: https://issues.redhat.com/browse/RHEL-40217

**Comment by aciba90** [comment]
Thanks, @benj-n. https://issues.redhat.com/browse/RHEL-40217 is not public, is it possible to share it?

I am going to mark this one as invalid.

**Comment by benj-n** [comment]
Unfortunately, I'm a simple user reporting an issue: I don't think I'm entitled to change the visibility of RHEL bug reports.
