### ISSUE TITLE
[enhancement]: rh_subscription module attribute org has the wrong schema

### ISSUE THREAD

**Issue by pneigel-ca** [canonical/cloud-init#5382]
# Enhancement

When using the rh_subscription module, I was referring to the documentation and getting tripped up on the schema for `org`. I observed that the schema defines this value should be type `integer`. I attempted to identify the `integer` value with RedHat support and we could not get it working.

After some back and forth, we identified the appropriate value for this was a `string`, ex `ABC`. As a result of using a string value, cloud-init throws a schema error:

<img width="680" alt="image" src="https://github.com/canonical/cloud-init/assets/48532268/49e752e1-ef77-4979-9078-1da4db2f74d5">

The schema should be updated and documentation should be updated to match the working implementation determined with the help of RedHat support.

**Comment by aciba90** [comment]
Thanks for reporting this. You are right, the --org argument for subscription-manager is string and not integer: https://github.com/candlepin/subscription-manager/blob/b6fad11e7783ae414fe88fdecee57d8db5c8e292/man/subscription-manager.8#L589

We have to change its type to "string" in: https://github.com/canonical/cloud-init/blob/fc2134bed02571f68678f0fe0457ef06134c94d9/cloudinit/config/schemas/schema-cloud-config-v1.json#L2481

**Comment by pneigel-ca** [comment]
@aciba90 Thank you for your guidance on this issue. I opened a PR for this.
