### ISSUE TITLE
azure: imds retry time() vs. monotonic()

### ISSUE THREAD

**Issue by cjp256** [canonical/cloud-init#5421]
Transient IMDS failures are not being retried.  Description and fix:
https://github.com/canonical/cloud-init/pull/5420

**Comment by cjp256** [comment]
I guess "New Issue" when looking at milestone doesn't mean it sets it to the milestone...  Please include for 23.2, thanks!

**Comment by holmanb** [comment]
We'll release 23.2... someday.

I just added this to the milestone.

**Comment by blackboxsw** [comment]
It looks like #5420 is merged. I'll mark this closed as a result of that issue. Please re-open if I'm mistaken here and another fix is still needed.
