### ISSUE TITLE
[docs]: missing redirect for topics/integration_tests

### ISSUE THREAD

**Issue by a-dubs** [canonical/cloud-init#5425]
# Documentation request

Started on:
https://cloudinit.readthedocs.io/en/22.4.2/topics/integration_tests.html

Clicked on the version switcher in the bottom left and clicked on latest and it took me to:
https://cloudinit.readthedocs.io/en/latest/topics/integration_tests.html

*Note: This broke when i tried switching to anything 23.X and newer (latest and stable included).

**Comment by a-dubs** [comment]
Correct redirect should be to:
https://cloudinit.readthedocs.io/en/latest/development/integration_tests.html

**Comment by blackboxsw** [comment]
Thanks @a-dubs! Just added  redirect rules in RTD topics/integration_tests.html -> development/integration_tests.html. Validated working redirect.

**Comment by a-dubs** [comment]
Yay, thanks! @blackboxsw
