### ISSUE TITLE
[enhancement]: Support downloading file contents with `write_files` module

### ISSUE THREAD

**Issue by LRitzdorf** [canonical/cloud-init#5500]
# Enhancement

## Proposal

We propose the addition of an extra key to the `write_files` module (something along the lines of `source`?) which would accept a URI from which to retrieve file contents. This would conflict with the existing `content` key, i.e. only one or the other would be allowed at a time.

## Reasoning

Currently, it is only possible to specify file contents inline, via the `write_files` module's `content` key. This poses a number of difficulties, notably for cases such as:
- Files produced via inter-team collaboration
  - Combining multiple cloud-configs is impractical, since either a) later `write_file` invocations with the same target would overwrite previous ones, or b) if the `append` option is set, the configuration ceases to become idempotent.
  - Some use-cases may require one team to remove or edit content created by another team, which is impossible via simple appending to the target file.
- Files which must change frequently, especially in an automated workflow
  - While automation tools could, in some cases, touch the cloud-init config directly, it is far simpler for them to expose their outputs for download by cloud-init clients.
- Large binary files
  - Encoding into base64, as is required when including binary files in a cloud-init configuration, introduces a 33% space overhead. Removing this could be beneficial for network performance.
  - From an aesthetic perspective, throwing a block of base64 into an otherwise human-readable YAML document is awkward. Including a download URL for the relevant content should be significantly cleaner.

These challenges could be (and, in some cases, likely are) accomplished via preprocessing by the cloud-init server. However, this would require the use of a template-like language embedded into the cloud-init config, which is likely to be both work-intensive and unnecessarily painful.

We envision a use case such as the following:

> In an HPC cluster, nodes are configured via cloud-init. Configurations are managed by multiple teams, who may need to touch the same sets of files (for example, an MPI config), and therefore cannot be created using multiple `write_files` invocations, as later ones would simply overwrite their earlier counterparts.
> The desired configurations could be managed by the teams in a collaborative Git repository, accessible from the cluster. During configuration, cloud-init could retrieve the desired configuration file(s) and write them to the desired location.

**Comment by LRitzdorf** [comment]
Also, I'm prepared to (at least begin) PRing this. The actual download logic (URI parsing, protocol handling, etc) seems likely to be the most difficult, though if I'm lucky there may already be functionality for this which I can hook into.

**Comment by TheRealFalcon** [comment]
@LRitzdorf , thanks for the proposal and thinking through the details. The idea sounds good to me. PRs are always welcome!

> The actual download logic (URI parsing, protocol handling, etc) seems likely to be the most difficult, though if I'm lucky there may already be functionality for this which I can hook into.

There are some pre-existing helpers you can use . This is a probably a good starting point:

https://github.com/canonical/cloud-init/blob/7130bbbb146a0d6612c11c44b82a65e6c1cd97aa/cloudinit/url_helper.py#L219

Feel free to ask any questions here or in our IRC channel in #cloud-init on Libera.

**Comment by LRitzdorf** [comment]
All right, the associated PR is ready for initial review. I have a few implementation questions in the comments there, but core functionality is complete.
