### ISSUE TITLE
Missing possible values for chef

### ISSUE THREAD

**Issue by blackknight36** [canonical/cloud-init#5513]
# Documentation request

The documentation for chef attributes is not complete and does not explain what possible values are for some keys.

---
*Reported from: https://docs.cloud-init.io/en/latest/reference/modules.html

**Comment by aciba90** [comment]
Thanks, @blackknight36, for reporting this. Could you elaborate on what fields are not complete?

**Comment by blackknight36** [comment]
> https://docs.cloud-init.io/en/latest/reference/modules.html

For example, `chef_license`

The docs state > chef_license: (string) string that indicates if user accepts or not license related to some of chef products

What are the possible values?  What is the default?  I had to look through the chef documentation to find out.

**Comment by blackknight36** [comment]
I'm happy to submit a PR if needed.

**Comment by aciba90** [comment]
> I'm happy to submit a PR if needed.

Please do. Bear in mind that we probably do not want to over document every Chef's detail, as some of those possible values are likely to change in the future if cloud-init pass them to Chef. Thanks!

**Comment by aciba90** [comment]
See https://docs.cloud-init.io/en/latest/development/index.html and https://docs.cloud-init.io/en/latest/development/contribute_docs.html for guidance on how to do your first contribution.
