### ISSUE TITLE
[docs]: cc_users_groups.user attributes not shown in the documentation

### ISSUE THREAD

**Issue by aciba90** [canonical/cloud-init#5514]
# Documentation request

Latest docs do not show the subkeys in [cc_users_groups.user](https://github.com/canonical/cloud-init/blob/e0e6a427fdc6826bf7b11d52157a1c5f9b3dde4d/cloudinit/config/schemas/schema-cloud-config-v1.json#L213), see attached screenshot.

But https://docs.cloud-init.io/en/23.1/reference/modules.html#users-and-groups show them.

![image](https://github.com/user-attachments/assets/74b2d328-8a27-4f9a-95c6-208b0b55b21c)

---
*Reported from: https://docs.cloud-init.io/en/latest/reference/modules.html*

**Comment by blackboxsw** [comment]
This is definitely related to recent doc migration changes. We should resolve this as it's a regression in doc rendering
