### ISSUE TITLE
Yum repo should accept mirrorlist instead of baseurl in the Yum Add Repo module 

### ISSUE THREAD

**Issue by val-gord** [canonical/cloud-init#5520]
# Bug report
cloud-init refuses to add a yum repository which has only a `mirrorlist` field and not a `baseurl` field. This is a valid repository configuration for repositories who provide a list of mirrors to clients as opposed to a single `baseurl`. The `mirorlist` url points to a URL containing a list of URLs, all of which YUM will treat as baseurls, this allows load balancing etc. It can exist either instead of `baseurl` in which case its used in all cases, or as well as in which case its used as a fallback.

For example see:
https://jsmith.fedorapeople.org/drafts/SMG/html/Software_Management_Guide/ch04s08s06.html

This issue is almost identical to this one: https://github.com/canonical/cloud-init/issues/5359 except that it refers to the `mirrorlist` parameter as an alternative to `baseurl` instead of `metalink`.  Any one of the three (or a combination of them) should be acceptable as a repository configuration. The fix should also be essentially identical to this other issue.

## Steps to reproduce the problem
Create a cloud init file with a yum_repos section similar to this:
```
yum_repos:
  <REDACTED>:
    name: A YUM Repo
    mirrorlist: https://<REDACTED>/mirror.list
    type: rpm-md
    enabled_metadata: 1
```
cloud init will skip adding the repository in question with the error below

## Environment details
- Cloud-init version: 22.2.2
- Operating System Distribution: Amazon Linux 2023
- Cloud provider, platform or installer type: NoCloud (offline device with seed files)

## cloud-init logs
```
cc_yum_add_repo.py[WARNING]: Repository <REDACTED> does not contain a baseurl configuration 'required' entry
cc_yum_add_repo.py[WARNING]: Repository <REDACTED> is missing 1 required fields, skipping!
```

**Comment by val-gord** [comment]
@ani-sinha Just adding you for visibility as this is almost identical to the issue you worked on 3 weeks ago.

**Comment by aciba90** [comment]
Thanks, @val-gord and @ani-sinha, for reporting this and fixing it. As https://github.com/canonical/cloud-init/issues/5359 was, this is an enhancement rather than a bug.
