### ISSUE TITLE
resize fails with btrfs-progs 6.10+ because of unexpected new output in `btrfs --version`

### ISSUE THREAD

**Issue by AdamWill** [canonical/cloud-init#5614]
# Bug report
cloud-init resize fails due to unexpected content in `btrfs --version` output in 6.10.

## Steps to reproduce the problem
try and use cloud-init to resize a btrfs filesystem, with btrfs-progs 6.10 installed.

## Environment details
- Cloud-init version: 24.2
- Operating System Distribution: Fedora Rawhide
- Cloud provider, platform or installer type: irrelevant

## cloud-init logs
```
2024-08-13 09:16:45,278 - util.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.13/site-packages/cloudinit/config/cc_resizefs.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/cloudinit/config/modules.py", line 286, in _run_modules
    ran, _r = cc.run(
              ~~~~~~^
        run_name, mod.handle, func_args, freq=freq
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/cloudinit/cloud.py", line 71, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/cloudinit/helpers.py", line 156, in run
    results = functor(**args)
  File "/usr/lib/python3.13/site-packages/cloudinit/config/cc_resizefs.py", line 306, in handle
    resize_cmd = resizer(resize_what, devpth)
  File "/usr/lib/python3.13/site-packages/cloudinit/config/cc_resizefs.py", line 60, in _resize_btrfs
    system_btrfs_ver = util.Version.from_str(
        subp.subp(["btrfs", "--version"])[0].split("v")[-1].strip()
    )
  File "/usr/lib/python3.13/site-packages/cloudinit/util.py", line 3164, in from_str
    return cls(*(list(map(int, version.split(".")))))
                 ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10\n-EXPERIMENTAL -INJECT -STATIC +LZO +ZSTD +UDEV +FSVERITY +ZONED CRYPTO=libgcrypt'
```

This is because, as of 6.10.0, btrfs-progs added an extra line of output to the `btrfs --version` output:
```
[adamw@xps13a tmp]$ btrfs --version
btrfs-progs v6.10
-EXPERIMENTAL -INJECT -STATIC +LZO +ZSTD +UDEV +FSVERITY +ZONED CRYPTO=libgcrypt
```
The fix for this is trivial, but I am not submitting it because doing so requires signing the Canonical CLA; I work for Red Hat and it's not on the list of CLAs we're approved to sign. I suggest you implement the obvious fix for this independently without looking at any Fedora package repositories where I might be putting my version of it, and then we can all not bother any lawyers about it. :D

**Comment by blackboxsw** [comment]
@AdamWill thanks for filing the bug and improving cloud-init (and hopefully allowing us to provide a fix which avoids you having to carry downstream patches long-term for this). @holmanb is on the fix looks like already so we should have this committed in upstream  today.

**Comment by AdamWill** [comment]
Thanks a lot for the prompt fix!

**Comment by holmanb** [comment]
> Thanks a lot for the prompt fix!

The solution was (as you said) trivial, so thanks for reporting it in this way :)

We do have multiple Red Hat employees who regularly contribute. I would have to check, but there might be an organizational (not an individual) CLA agreement in place for Red Hat. If this comes up again, you might internally ping one of your coworkers that contributes regularly for the guidance that they received from your legal team - otherwise we could try to dig into it, but that would involve us trying to extract helpful guidance from our own legal team :(

Either way, cheers and thanks for the contribution @AdamWill!

**Comment by AdamWill** [comment]
yeah, I noticed the same and that might well be the case, but since this was trivial I figured this was the easiest way to handle it. If I ever have anything more substantial to contribute I'll look into it in more detail. thanks again!

**Comment by AkihiroSuda** [comment]
ArchLinux 20240815.255016 is not bootable due to this issue.

Any chance to get a new release with the fix so that ArchLinux can package it in the next image release?

**Comment by holmanb** [comment]
> ArchLinux 20240815.255016 is not bootable due to this issue.
> 
> Any chance to get a new release with the fix so that ArchLinux can package it in the next image release?

Thanks for reporting @AkihiroSuda. Have you tested the fix?

A new upstream release is planned for next week, otherwise feel free to pull in a patch into downstream if a faster fix is required.
