### ISSUE TITLE
status prints extra empty line with --wait flag

### ISSUE THREAD

**Issue by aciba90** [canonical/cloud-init#5683]
# Bug report

`cloud-init status --wait` prints an extra line at the begining of stdout that it is not printed in `cloud-init status`.

## Steps to reproduce the problem

```
root@vmo:~# apt policy cloud-init
cloud-init:
  Installed: 24.4~3+really24.3.1-0ubuntu1
  Candidate: 24.4~3+really24.3.1-0ubuntu1
  Version table:
 *** 24.4~3+really24.3.1-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu oracular/main amd64 Packages
        100 /var/lib/dpkg/status
root@vmo:~# cloud-init status
status: done
root@vmo:~# cloud-init status --wait

status: done
root@vmo:~# cloud-init status --wait --long

status: done
extended_status: done
boot_status_code: enabled-by-generator
last_update: Thu, 01 Jan 1970 00:00:11 +0000
detail: DataSourceLXD
errors: []
recoverable_errors: {}
```

## Environment details
- Cloud-init version: 24.4~3+really24.3.1-0ubuntu1
- Operating System Distribution: Ubuntu
- Cloud provider, platform or installer type: lxd vm

## cloud-init logs

N/A

**Comment by nelsonad-ops** [comment]
Hi, I would like to work on this issue. Thanks!

**Comment by aciba90** [comment]
Thanks, @nelsonad-ops, for making cloud-init better. Please go on and propose a PR. See [How to contribute to cloud-init](https://docs.cloud-init.io/en/latest/development/index.html) for reference.

**Comment by holmanb** [comment]
Fixed in https://github.com/canonical/cloud-init/pull/5700
