### ISSUE TITLE
Cloud-init schema command shouldn't require sudo

### ISSUE THREAD

**Issue by holmanb** [canonical/cloud-init#5743]
# Bug report
When `cloud-init schema -c ./tmp.yml` runs without sudo, we see permissions warnings:

```bash
cloud-init schema -c ./tmp.yml
2024-09-24 20:07:05,661 - sources[WARNING]: failed loading pickle in /var/lib/cloud/instance/obj.pkl: [Errno 13] Permission denied: '/var/lib/cloud/instance/obj.pkl'
Valid schema ./tmp.yml
ubuntu@me:~$ echo $?
0
$ cloud-init schema -t network-config -c ./50-cloud-init.yaml
2024-09-24 20:10:13,968 - sources[WARNING]: failed loading pickle in /var/lib/cloud/instance/obj.pkl: [Errno 13] Permission denied: '/var/lib/cloud/instance/obj.pkl'
Valid schema ./50-cloud-init.yaml
ubuntu@me:~$ echo $?
0
```

This command is simple verification of a configuration file, and shouldn't require running with elevated permissions.

## Fix

Besides just fixing this, we should add test coverage to the integration testing framework.

**Comment by blackboxsw** [comment]
Correct, we shouldn't be referencing the obj.pkl for schema validation. Though there may be cases where tmp.yml is declared as a jinja template and we'd potentially want to reference a JSON-dict of jinja variables. I suppose in those specific cases, we'd want to require --instance-data param if jinja-template and the default location /run/cloud-init/instance-data.son doesn't exist.

**Comment by TheRealFalcon** [comment]
Duplicate. See https://github.com/canonical/cloud-init/issues/4709
