### ISSUE TITLE
[docs]: `wsl --list` not output downloaded image from Microsoft Store

### ISSUE THREAD

**Issue by minhtaile2712** [canonical/cloud-init#5746]
On this link [WSL Tutorial](https://docs.cloud-init.io/en/latest/tutorial/wsl.html), the tutorial claims that
- downloading the [Ubuntu 24.04](https://apps.microsoft.com/detail/9nz3klhxdjp5) WSL image from the Microsoft Store, then
- running the command `wsl --list` will show `Ubuntu-24.04` in the list of available WSL instances.

Which is not correct, effectively make the `Option #1` of the tutorial invalid.

If follow the [`Option #1`](https://docs.cloud-init.io/en/latest/tutorial/wsl.html#option-1-the-microsoft-store), the later command `wsl --distribution Ubuntu-24.04` will fail with this output:
```
There is no distribution with the supplied name.
Error code: Wsl/Service/WSL_E_DISTRO_NOT_FOUND
```

Please fix this option or remove it if not applicable.

The solution from [Automatic setup with cloud-init](https://docs.cloud-init.io/en/latest/tutorial/wsl.html#option-1-the-microsoft-store) providing this command `ubuntu2404.exe install --root` may solve the problem of `wsl --distribution Ubuntu-24.04`.

Tested system:
```
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.4169
```

**Comment by TheRealFalcon** [comment]
@minhtaile2712 , thanks for filing the issue. I have a PR up at https://github.com/canonical/cloud-init/pull/5752 to address this.
