### ISSUE TITLE
cloud.cfg.tmpl entry "resize_rootfs_tmp" appears to have no purpose

### ISSUE THREAD

**Issue by dermotbradley** [canonical/cloud-init#5786]
# Bug report

The cloud.cfg.tmpl template file includes the line "resize_rootfs_tmp: /dev". However I can find no code that makes use of a "resize_rootfs_tmp" configuration setting and it is not mentioned in the schemas.

## Environment details
- Cloud-init version: git main
- Operating System Distribution: n/a
- Cloud provider, platform or installer type: n/a

## cloud-init logs

Not relevant.

**Comment by TheRealFalcon** [comment]
Thanks @dermotbradley . Looks like it was removed in ed8f1b159174715403cb1ffa200ff6d080770152 . We can remove it from the template.
