### ISSUE TITLE
[enhancement]: docker local run

### ISSUE THREAD

**Issue by libmonsoon-dev** [canonical/cloud-init#5834]
The [documentation](https://cloudinit.readthedocs.io/en/latest/howto/run_cloud_init_locally.html) describes ways to run locally for configuration tests using virtual machines.
Is it possible to implement and/or doc a similar run in a local docker? This would give a big performance boost at least for Linux workstations. Not to mention reduced consumption of storage and additional features such as layer caching.

**Comment by TheRealFalcon** [comment]
@libmonsoon-dev , the recommended way of running cloud-init within containers locally is using [LXD](https://cloudinit.readthedocs.io/en/latest/howto/run_cloud_init_locally.html#lxd). For most linux distros, cloud-init requires systemd, and [systemd is not recommended to run within a docker container](https://forums.docker.com/t/dockerfile-with-debian-systemd/141622/2).

If you've never used LXD, the docs contain a [quick-start tutorial](https://docs.cloud-init.io/en/latest/tutorial/lxd.html) using cloud-init with LXD.
