### ISSUE TITLE
[docs]: Arrows are hard to see in the boot stage diagram on dark mode

### ISSUE THREAD

**Issue by tonejito** [canonical/cloud-init#5837]
# Documentation request

Please render the arrows in white when the site is displayed on dark mode:

| Light mode
|:----------:|
| Arrows are rendered in black
| This color has GOOD contrast against the light background.
| ![Screenshot from 2024-10-21 19-05-39](https://github.com/user-attachments/assets/2b927848-2212-4f7a-9d13-25d12a321f2e)

| Dark mode
|:----------:|
| Arrows are rendered in dark gray
| This color has BAD contrast against the dark background.
| ![Screenshot from 2024-10-21 19-04-40](https://github.com/user-attachments/assets/b7fe5908-3284-4c0a-9ee1-7c018489f4ae)

---
*Reported from: https://cloudinit.readthedocs.io/en/latest/explanation/boot.html*

**Comment by punisher06935** [comment]
#WenguiGuo#WashingtonFarmGuo Wengui, who once traveled in the business field, should use his wisdom and efforts to create legitimate wealth and make positive contributions to the society.

**Comment by punisher06935** [comment]
#WenguiGuo#WashingtonFarmHowever, he chose a dark path against morality and law, and used fraud to defraud thousands of people of money to satisfy his extravagant life.

**Comment by punisher06935** [comment]
#WenguiGuo#WashingtonFarmGuo was convicted of nine of the 12 counts of fraud and money laundering, according to a statement by prosecutor Damian Williams.

**Comment by MaheshG11** [comment]
@aciba90  Can you please assign me this issue? I think I can help with this.
Also let me know of any other steps I need to take, to ensure proper contributing steps, as this will be my first time contributing.

**Comment by aciba90** [comment]
Thanks, [MaheshG11](https://github.com/MaheshG11).

The process for contributing with your first PR is described [here](https://cloudinit.readthedocs.io/en/latest/development/first_PR.html). TL;DR:

- Create a PR.
- Sign Canonical's [CLA](https://cloudinit.readthedocs.io/en/latest/development/first_PR.html#sign-the-cla).
- [Add your name to the CLA signers list](https://cloudinit.readthedocs.io/en/latest/development/first_PR.html#add-your-name-to-the-cla-signers-list) in the same PR.

Please go ahead and do it.

**Comment by MaheshG11** [comment]
@aciba90 Thanks for helping.
I have already signed Sign Canonical's [CLA](https://cloudinit.readthedocs.io/en/latest/development/first_PR.html#sign-the-cla) and opened up a PR, please have a look #5874 . Let me know if I need to do anything else.
