### ISSUE TITLE
TODO: Patch grub-dpkg support

### ISSUE THREAD

**Issue by holmanb** [canonical/cloud-init#5842]
# Bug report
Reminder to patch out https://github.com/canonical/cloud-init/pull/5840 in oracular and earlier.

**Comment by TheRealFalcon** [comment]
Oracular and earlier or Jammy and earlier?

**Comment by holmanb** [comment]
> Oracular and earlier or Jammy and earlier?

Oracular and earlier, I think. It should be a no-op on Noble and later, but just to be sure we don't want want to make the change until Puffin.

**Comment by TheRealFalcon** [comment]
Oracular PR: https://github.com/canonical/cloud-init/pull/5859

**Comment by TheRealFalcon** [comment]
Based on https://github.com/canonical/cloud-init/pull/5859 , I also patched noble, jammy, and focal, so I'm closing this issue.
